//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resto.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resto.Framework.Properties.ResourceFile", typeof(ResourceFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;x:stylesheet version=&quot;1.0&quot; xmlns:x=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;x:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;
        ///
        ///  &lt;x:template match=&quot;@*|node()&quot;&gt;
        ///    &lt;x:copy&gt;
        ///      &lt;x:apply-templates select=&quot;@*|node()&quot;/&gt;
        ///    &lt;/x:copy&gt;
        ///  &lt;/x:template&gt;
        ///
        ///  &lt;x:template match=&quot;line&quot;&gt;
        ///    &lt;x:choose&gt;
        ///      &lt;x:when test=&quot;@symbols&quot;&gt;
        ///        &lt;fill symbols=&quot;{@symbols}&quot;&gt;
        ///          &lt;np /&gt;
        ///        &lt;/fill&gt;
        ///      &lt;/x:when&gt;
        ///      &lt;x:otherwise&gt;
        ///        &lt;fill symbols=&quot;-&quot;&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocPreprocess {
            get {
                return ResourceManager.GetString("DocPreprocess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema xmlns:mstns=&quot;http://iiko.ru/Doc.xsd&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; id=&quot;Doc&quot;&gt;
        ///  &lt;xs:element name=&quot;doc&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:complexContent&gt;
        ///        &lt;xs:extension base=&quot;anyInput&quot;&gt;
        ///          &lt;xs:attribute name=&quot;bell&quot; type=&quot;xs:string&quot;&gt;
        ///            &lt;xs:annotation&gt;
        ///              &lt;xs:documentation&gt;
        ///                Включение кухонного звонка перед началом печати документа.
        ///                Примечания:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Schema {
            get {
                return ResourceManager.GetString("Schema", resourceCulture);
            }
        }
    }
}
