//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resto.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resto.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить....
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Алгоритм.
        /// </summary>
        public static string Algorithm {
            get {
                return ResourceManager.GetString("Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть все.
        /// </summary>
        public static string BaseTabManagerCloseAll {
            get {
                return ResourceManager.GetString("BaseTabManagerCloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть все, кроме текущей.
        /// </summary>
        public static string BaseTabManagerCloseAllExceptCurrent {
            get {
                return ResourceManager.GetString("BaseTabManagerCloseAllExceptCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас нет прав для просмотра данной информации.
        /// </summary>
        public static string BaseTabManagerNoRightsToViewInformation {
            get {
                return ResourceManager.GetString("BaseTabManagerNoRightsToViewInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancellation {
            get {
                return ResourceManager.GetString("Cancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный шаблон для считывателя карт.
        /// </summary>
        public static string CardProcessorInvalidPattern {
            get {
                return ResourceManager.GetString("CardProcessorInvalidPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Префикс считывателя карт не должен заканчиваться на символ *.
        /// </summary>
        public static string CardProcessorInvalidPrefix {
            get {
                return ResourceManager.GetString("CardProcessorInvalidPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суффикс считывателя карт не должен начинаться с символа *.
        /// </summary>
        public static string CardProcessorInvalidSuffix {
            get {
                return ResourceManager.GetString("CardProcessorInvalidSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [значение не определено].
        /// </summary>
        public static string ChildObjectConverter_ConvertTo {
            get {
                return ResourceManager.GetString("ChildObjectConverter_ConvertTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        public static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить все.
        /// </summary>
        public static string ClearAllAction {
            get {
                return ResourceManager.GetString("ClearAllAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string CloseAction {
            get {
                return ResourceManager.GetString("CloseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скопировать в буфер обмена.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдена секция данных.
        /// </summary>
        public static string CryptoContainerHelperDataSectionNotFound {
            get {
                return ResourceManager.GetString("CryptoContainerHelperDataSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при обработке файла: {0}.
        /// </summary>
        public static string CryptoContainerHelperFileProcessingError {
            get {
                return ResourceManager.GetString("CryptoContainerHelperFileProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат файла..
        /// </summary>
        public static string CryptoContainerHelperInvalidFileFormat {
            get {
                return ResourceManager.GetString("CryptoContainerHelperInvalidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат файла: атрибут &apos;{0}&apos; не найден..
        /// </summary>
        public static string CryptoContainerHelperInvalidFileFormatAttributeNotFound {
            get {
                return ResourceManager.GetString("CryptoContainerHelperInvalidFileFormatAttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат файла: невозможно интерпретировать значение &apos;{0}&apos;..
        /// </summary>
        public static string CryptoContainerHelperInvalidFileFormatCanNotInterpretValue {
            get {
                return ResourceManager.GetString("CryptoContainerHelperInvalidFileFormatCanNotInterpretValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат XML:{0}.
        /// </summary>
        public static string CryptoContainerHelperInvalidXMLFormat {
            get {
                return ResourceManager.GetString("CryptoContainerHelperInvalidXMLFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная версия контейнера &apos;{0}&apos;.
        /// </summary>
        public static string CryptoContainerHelperUnknownContainerVersion {
            get {
                return ResourceManager.GetString("CryptoContainerHelperUnknownContainerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неподдерживаемое значение &apos;{0}&apos; для атрибута &apos;{1}&apos;.
        /// </summary>
        public static string CryptoContainerHelperUnsupportedAttributeValue {
            get {
                return ResourceManager.GetString("CryptoContainerHelperUnsupportedAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вырезать.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to день.
        /// </summary>
        public static string DayForm1 {
            get {
                return ResourceManager.GetString("DayForm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дня.
        /// </summary>
        public static string DayForm2 {
            get {
                return ResourceManager.GetString("DayForm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дней.
        /// </summary>
        public static string DayForm3 {
            get {
                return ResourceManager.GetString("DayForm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to д..
        /// </summary>
        public static string DayShortText {
            get {
                return ResourceManager.GetString("DayShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Библиотеки BDE не найдены. Попробуйте переустановить приложение..
        /// </summary>
        public static string DbiEnvironmentBDELibraryNotFoundTryReinstallApplication {
            get {
                return ResourceManager.GetString("DbiEnvironmentBDELibraryNotFoundTryReinstallApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка инициализации драйвера Paradox.{0}Возможно запущенны другие приложения использующие этот драйвер (например UCS StoreHouse, ImportRK).{0}Закройте эти приложения и повторите попытку.{0}{0}Код ошибки: .
        /// </summary>
        public static string DbiEnvironmentParadoxDriverInitializationError {
            get {
                return ResourceManager.GetString("DbiEnvironmentParadoxDriverInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение.
        /// </summary>
        public static string DefaultConfirmationDialogCaption {
            get {
                return ResourceManager.GetString("DefaultConfirmationDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить....
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление.
        /// </summary>
        public static string DeleteActionCaption {
            get {
                return ResourceManager.GetString("DeleteActionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить все элементы?.
        /// </summary>
        public static string DeleteAllItemsQuestion {
            get {
                return ResourceManager.GetString("DeleteAllItemsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить выбранный элемент?.
        /// </summary>
        public static string DeleteSelectedItemQuestion {
            get {
                return ResourceManager.GetString("DeleteSelectedItemQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить выбранные элементы?.
        /// </summary>
        public static string DeleteSelectedItemsQuestion {
            get {
                return ResourceManager.GetString("DeleteSelectedItemsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to События.
        /// </summary>
        public static string Developments {
            get {
                return ResourceManager.GetString("Developments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;x:stylesheet version=&quot;1.0&quot; xmlns:x=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;x:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;
        ///
        ///  &lt;x:template match=&quot;@*|node()&quot;&gt;
        ///    &lt;x:copy&gt;
        ///      &lt;x:apply-templates select=&quot;@*|node()&quot;/&gt;
        ///    &lt;/x:copy&gt;
        ///  &lt;/x:template&gt;
        ///
        ///  &lt;x:template match=&quot;line&quot;&gt;
        ///    &lt;x:choose&gt;
        ///      &lt;x:when test=&quot;@symbols&quot;&gt;
        ///        &lt;fill symbols=&quot;{@symbols}&quot;&gt;
        ///          &lt;np /&gt;
        ///        &lt;/fill&gt;
        ///      &lt;/x:when&gt;
        ///      &lt;x:otherwise&gt;
        ///        &lt;fill symbols=&quot;-&quot;&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DocPreProcess {
            get {
                return ResourceManager.GetString("DocPreProcess", resourceCulture);
            }
        }
        
      
        /// <summary>
        ///   Looks up a localized string similar to Редактировать....
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры шифрования.
        /// </summary>
        public static string EncryptionOptions {
            get {
                return ResourceManager.GetString("EncryptionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string ErrorMessageCaption {
            get {
                return ResourceManager.GetString("ErrorMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xlsx.
        /// </summary>
        public static string ExcelExportControlDefaultExcelFileExtension {
            get {
                return ResourceManager.GetString("ExcelExportControlDefaultExcelFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно выполнить экспорт. Возможные причины:
        ///    1) Превышено допустимое количество колонок (256) или строк (65536). Попробуйте выполнить экспорт в формат XLSX.
        ///    2) Запущен MS Excel.
        /// </summary>
        public static string ExcelExportControlDefaultExportErrorMessage {
            get {
                return ResourceManager.GetString("ExcelExportControlDefaultExportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно выполнить экспорт. Превышено допустимое количество колонок - 256..
        /// </summary>
        public static string ExcelExportControlMaxColumnErrorMessage {
            get {
                return ResourceManager.GetString("ExcelExportControlMaxColumnErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных для экспорта.
        /// </summary>
        public static string ExcelExportControlNoDataForExport {
            get {
                return ResourceManager.GetString("ExcelExportControlNoDataForExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось открыть файл(ы):.
        /// </summary>
        public static string ExcelFilesPostprocessorFailedOpenFile {
            get {
                return ResourceManager.GetString("ExcelFilesPostprocessorFailedOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт в MS Excel.
        /// </summary>
        public static string ExportToMSExcel {
            get {
                return ResourceManager.GetString("ExportToMSExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По умолчанию.
        /// </summary>
        public static string FieldChooserDefault {
            get {
                return ResourceManager.GetString("FieldChooserDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите новое имя колонки:.
        /// </summary>
        public static string FieldChooserEnterNewColumnName {
            get {
                return ResourceManager.GetString("FieldChooserEnterNewColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оптимальная ширина.
        /// </summary>
        public static string FieldChooserOptimalWidth {
            get {
                return ResourceManager.GetString("FieldChooserOptimalWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переименовать....
        /// </summary>
        public static string FieldChooserRename {
            get {
                return ResourceManager.GetString("FieldChooserRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Несохраненные изменения будут утеряны. Продолжить?.
        /// </summary>
        public static string GuiUtilContinueWithUnsavedDataMessage {
            get {
                return ResourceManager.GetString("GuiUtilContinueWithUnsavedDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string GuiUtilInfoMessageCaption {
            get {
                return ResourceManager.GetString("GuiUtilInfoMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить изменения?.
        /// </summary>
        public static string GuiUtilSaveDataQuestionMessage {
            get {
                return ResourceManager.GetString("GuiUtilSaveDataQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        public static string GuiUtilWarningMessageCaption {
            get {
                return ResourceManager.GetString("GuiUtilWarningMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не может быть null..
        /// </summary>
        public static string HelpFileNameIsNull {
            get {
                return ResourceManager.GetString("HelpFileNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Класс должен быть проинициализирован вызовом метода Initialize()..
        /// </summary>
        public static string HelpHelperClassMustBeInitialize {
            get {
                return ResourceManager.GetString("HelpHelperClassMustBeInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документация отсутствует..
        /// </summary>
        public static string HelpHelperNoAnyDocumentation {
            get {
                return ResourceManager.GetString("HelpHelperNoAnyDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка конфигурации.
        /// </summary>
        public static string HelpHelperShowPopupRestaurantSettings {
            get {
                return ResourceManager.GetString("HelpHelperShowPopupRestaurantSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ч..
        /// </summary>
        public static string HourShortText {
            get {
                return ResourceManager.GetString("HourShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введены неверные данные.
        /// </summary>
        public static string IncorrectlyEnteredData {
            get {
                return ResourceManager.GetString("IncorrectlyEnteredData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка ввода.
        /// </summary>
        public static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Префикс Кодос не должен заканчиваться на символ *.
        /// </summary>
        public static string KodosRDProcessor_SerialPortDataReceivedPrefix {
            get {
                return ResourceManager.GetString("KodosRDProcessor_SerialPortDataReceivedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суффикс Кодос не должен начинаться с символа *.
        /// </summary>
        public static string KodosRDProcessor_SerialPortDataReceivedSuffix {
            get {
                return ResourceManager.GetString("KodosRDProcessor_SerialPortDataReceivedSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мин..
        /// </summary>
        public static string MinuteShortText {
            get {
                return ResourceManager.GetString("MinuteShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мес..
        /// </summary>
        public static string MonthShortText {
            get {
                return ResourceManager.GetString("MonthShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книжная.
        /// </summary>
        public static string MsHtmlHelperBook {
            get {
                return ResourceManager.GetString("MsHtmlHelperBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К&amp;нижная.
        /// </summary>
        public static string MsHtmlHelperBook1 {
            get {
                return ResourceManager.GetString("MsHtmlHelperBook1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альбомная.
        /// </summary>
        public static string MsHtmlHelperLandscape {
            get {
                return ResourceManager.GetString("MsHtmlHelperLandscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аль&amp;бомная.
        /// </summary>
        public static string MsHtmlHelperLandscape1 {
            get {
                return ResourceManager.GetString("MsHtmlHelperLandscape1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры страницы.
        /// </summary>
        public static string MsHtmlHelperPageSetup {
            get {
                return ResourceManager.GetString("MsHtmlHelperPageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string OfficeHelperInformation {
            get {
                return ResourceManager.GetString("OfficeHelperInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможно, не установлено ни одного приложения, ассоциированного с данным типом файлов..
        /// </summary>
        public static string OfficeHelperNoAnyApplicationAssociatedWithThatFileType {
            get {
                return ResourceManager.GetString("OfficeHelperNoAnyApplicationAssociatedWithThatFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть папку куда был сохранен файл?.
        /// </summary>
        public static string OfficeHelperOpenFolderWithSavedFile {
            get {
                return ResourceManager.GetString("OfficeHelperOpenFolderWithSavedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОК.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string OlapHelperNo {
            get {
                return ResourceManager.GetString("OlapHelperNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string OlapHelperYes {
            get {
                return ResourceManager.GetString("OlapHelperYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка устройства. {0}.
        /// </summary>
        public static string PCSCSmartCardReaderDeviceError {
            get {
                return ResourceManager.GetString("PCSCSmartCardReaderDeviceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency property &apos;{0}&apos; зарегистрирован с использованием стандартного типа метаданных, но для него не определена обертка в виде доступного (public) свойства. Определите обертку, либо воспользуйтесь метаданными типа &apos;HandleChangesPropertyMetadata&apos;..
        /// </summary>
        public static string RecordedUsingAStandardTypeOfMetadata {
            get {
                return ResourceManager.GetString("RecordedUsingAStandardTypeOfMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} д.
        /// </summary>
        public static string ReducedDay {
            get {
                return ResourceManager.GetString("ReducedDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ч.
        /// </summary>
        public static string ReducedHour {
            get {
                return ResourceManager.GetString("ReducedHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} мин.
        /// </summary>
        public static string ReducedMinute {
            get {
                return ResourceManager.GetString("ReducedMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется формирование отчета....
        /// </summary>
        public static string ReportGenerationIsPerformed {
            get {
                return ResourceManager.GetString("ReportGenerationIsPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введены неверные данные.
        /// </summary>
        public static string RepositoryItemRestoTextEditEnteredIncorrectData {
            get {
                return ResourceManager.GetString("RepositoryItemRestoTextEditEnteredIncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка ввода.
        /// </summary>
        public static string RepositoryItemRestoTextEditInputError {
            get {
                return ResourceManager.GetString("RepositoryItemRestoTextEditInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string RestoDoubleListName {
            get {
                return ResourceManager.GetString("RestoDoubleListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no common rule to implement this operation. Use BeforeCuttingObject event. Ошибка: {0}.
        /// </summary>
        public static string RestoGridClipboardDataCellFormerError {
            get {
                return ResourceManager.GetString("RestoGridClipboardDataCellFormerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список пуст.
        /// </summary>
        public static string RestoGridEmpty {
            get {
                return ResourceManager.GetString("RestoGridEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перетащите сюда заголовки столбцов, по которым необходимо сгруппировать данные.
        /// </summary>
        public static string RestoGridViewDragColumnTitlesToGroupData {
            get {
                return ResourceManager.GetString("RestoGridViewDragColumnTitlesToGroupData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск:.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сек..
        /// </summary>
        public static string SecondShortText {
            get {
                return ResourceManager.GetString("SecondShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать все.
        /// </summary>
        public static string SelectAllAction {
            get {
                return ResourceManager.GetString("SelectAllAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специфические параметры выбранного алгоритма шифрования.
        /// </summary>
        public static string SpecificParameters {
            get {
                return ResourceManager.GetString("SpecificParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавляемый контрол должен быть унаследован от BaseEdit, BaseCheckedListBoxControl из DevExpress.XtraEditors, либо реализовывать интерфейс IChangeable из Resto.Framework.UI.Common..
        /// </summary>
        public static string SubscribedControlWrapAddControlMustBeInheritedFrom {
            get {
                return ResourceManager.GetString("SubscribedControlWrapAddControlMustBeInheritedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список пуст.
        /// </summary>
        public static string TheListIsEmpty {
            get {
                return ResourceManager.GetString("TheListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . .
        /// </summary>
        public static string TimeSpanSuffix {
            get {
                return ResourceManager.GetString("TimeSpanSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип алгоритма шифрования.
        /// </summary>
        public static string TypeEncryptionAlgorithm {
            get {
                return ResourceManager.GetString("TypeEncryptionAlgorithm", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Looks up a localized string similar to нед..
        /// </summary>
        public static string WeekShortText {
            get {
                return ResourceManager.GetString("WeekShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить.
        /// </summary>
        public static string WizardControlLastNextText {
            get {
                return ResourceManager.GetString("WizardControlLastNextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Далее &gt;.
        /// </summary>
        public static string WizardControlNextText {
            get {
                return ResourceManager.GetString("WizardControlNextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно сохранить файл {0}:{1}.
        /// </summary>
        public static string XmlHelperImpossibleSaveFile {
            get {
                return ResourceManager.GetString("XmlHelperImpossibleSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to г..
        /// </summary>
        public static string YearShortText {
            get {
                return ResourceManager.GetString("YearShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
