//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resto.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TimeZones {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimeZones() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resto.Framework.Properties.TimeZones", typeof(TimeZones).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-12:00) Линия перемены дат.
        /// </summary>
        public static string Zone1 {
            get {
                return ResourceManager.GetString("Zone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-06:00) Гвадалахара, Мехико, Монтеррей.
        /// </summary>
        public static string Zone10 {
            get {
                return ResourceManager.GetString("Zone10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+13:00) Нукуалофа.
        /// </summary>
        public static string Zone100 {
            get {
                return ResourceManager.GetString("Zone100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+13:00) Самоа.
        /// </summary>
        public static string Zone101 {
            get {
                return ResourceManager.GetString("Zone101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-06:00) Саскачеван.
        /// </summary>
        public static string Zone11 {
            get {
                return ResourceManager.GetString("Zone11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-06:00) Центральная Америка.
        /// </summary>
        public static string Zone12 {
            get {
                return ResourceManager.GetString("Zone12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-06:00) Центральное время (США и Канада).
        /// </summary>
        public static string Zone13 {
            get {
                return ResourceManager.GetString("Zone13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-05:00) Богота, Кито, Лима.
        /// </summary>
        public static string Zone14 {
            get {
                return ResourceManager.GetString("Zone14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-05:00) Восточное время (США и Канада).
        /// </summary>
        public static string Zone15 {
            get {
                return ResourceManager.GetString("Zone15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-05:00) Индиана (восток).
        /// </summary>
        public static string Zone16 {
            get {
                return ResourceManager.GetString("Zone16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:30) Каракас.
        /// </summary>
        public static string Zone17 {
            get {
                return ResourceManager.GetString("Zone17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Асунсьон.
        /// </summary>
        public static string Zone18 {
            get {
                return ResourceManager.GetString("Zone18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Атлантическое время (Канада).
        /// </summary>
        public static string Zone19 {
            get {
                return ResourceManager.GetString("Zone19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-11:00) Время в формате UTC -11.
        /// </summary>
        public static string Zone2 {
            get {
                return ResourceManager.GetString("Zone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Джорджтаун, Ла-Пас, Манаус, Сан-Хуан.
        /// </summary>
        public static string Zone20 {
            get {
                return ResourceManager.GetString("Zone20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Куяба.
        /// </summary>
        public static string Zone21 {
            get {
                return ResourceManager.GetString("Zone21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Сантьяго.
        /// </summary>
        public static string Zone22 {
            get {
                return ResourceManager.GetString("Zone22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:30) Ньюфаундленд.
        /// </summary>
        public static string Zone23 {
            get {
                return ResourceManager.GetString("Zone23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Бразилия.
        /// </summary>
        public static string Zone24 {
            get {
                return ResourceManager.GetString("Zone24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Буэнос-Айрес.
        /// </summary>
        public static string Zone25 {
            get {
                return ResourceManager.GetString("Zone25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Гренландия.
        /// </summary>
        public static string Zone26 {
            get {
                return ResourceManager.GetString("Zone26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Кайенна, Форталеза.
        /// </summary>
        public static string Zone27 {
            get {
                return ResourceManager.GetString("Zone27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Монтевидео.
        /// </summary>
        public static string Zone28 {
            get {
                return ResourceManager.GetString("Zone28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Сальвадор.
        /// </summary>
        public static string Zone29 {
            get {
                return ResourceManager.GetString("Zone29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-10:00) Гавайи.
        /// </summary>
        public static string Zone3 {
            get {
                return ResourceManager.GetString("Zone3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-02:00) Время в формате UTC -02.
        /// </summary>
        public static string Zone30 {
            get {
                return ResourceManager.GetString("Zone30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-02:00) Среднеатлантическое время.
        /// </summary>
        public static string Zone31 {
            get {
                return ResourceManager.GetString("Zone31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-01:00) Азорские о-ва.
        /// </summary>
        public static string Zone32 {
            get {
                return ResourceManager.GetString("Zone32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-01:00) О-ва Зеленого Мыса.
        /// </summary>
        public static string Zone33 {
            get {
                return ResourceManager.GetString("Zone33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC) Время в формате UTC.
        /// </summary>
        public static string Zone34 {
            get {
                return ResourceManager.GetString("Zone34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC) Дублин, Лиссабон, Лондон, Эдинбург.
        /// </summary>
        public static string Zone35 {
            get {
                return ResourceManager.GetString("Zone35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC) Касабланка.
        /// </summary>
        public static string Zone36 {
            get {
                return ResourceManager.GetString("Zone36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC) Монровия, Рейкьявик.
        /// </summary>
        public static string Zone37 {
            get {
                return ResourceManager.GetString("Zone37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) Амстердам, Берлин, Берн, Вена, Рим, Стокгольм.
        /// </summary>
        public static string Zone38 {
            get {
                return ResourceManager.GetString("Zone38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) Белград, Братислава, Будапешт, Любляна, Прага.
        /// </summary>
        public static string Zone39 {
            get {
                return ResourceManager.GetString("Zone39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-09:00) Аляска.
        /// </summary>
        public static string Zone4 {
            get {
                return ResourceManager.GetString("Zone4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) Брюссель, Копенгаген, Мадрид, Париж.
        /// </summary>
        public static string Zone40 {
            get {
                return ResourceManager.GetString("Zone40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) Варшава, Загреб, Сараево, Скопье.
        /// </summary>
        public static string Zone41 {
            get {
                return ResourceManager.GetString("Zone41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) Виндхук.
        /// </summary>
        public static string Zone42 {
            get {
                return ResourceManager.GetString("Zone42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) Западная Центральная Африка.
        /// </summary>
        public static string Zone43 {
            get {
                return ResourceManager.GetString("Zone43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Амман.
        /// </summary>
        public static string Zone44 {
            get {
                return ResourceManager.GetString("Zone44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Афины, Бухарест.
        /// </summary>
        public static string Zone45 {
            get {
                return ResourceManager.GetString("Zone45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Бейрут.
        /// </summary>
        public static string Zone46 {
            get {
                return ResourceManager.GetString("Zone46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Вильнюс, Киев, Рига, София, Таллин, Хельсинки.
        /// </summary>
        public static string Zone47 {
            get {
                return ResourceManager.GetString("Zone47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Дамаск.
        /// </summary>
        public static string Zone48 {
            get {
                return ResourceManager.GetString("Zone48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Иерусалим.
        /// </summary>
        public static string Zone49 {
            get {
                return ResourceManager.GetString("Zone49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-08:00) Нижняя Калифорния.
        /// </summary>
        public static string Zone5 {
            get {
                return ResourceManager.GetString("Zone5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Каир.
        /// </summary>
        public static string Zone50 {
            get {
                return ResourceManager.GetString("Zone50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Никосия.
        /// </summary>
        public static string Zone51 {
            get {
                return ResourceManager.GetString("Zone51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Стамбул.
        /// </summary>
        public static string Zone52 {
            get {
                return ResourceManager.GetString("Zone52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Хараре, Претория.
        /// </summary>
        public static string Zone53 {
            get {
                return ResourceManager.GetString("Zone53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Багдад.
        /// </summary>
        public static string Zone54 {
            get {
                return ResourceManager.GetString("Zone54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Калиниград, Минск.
        /// </summary>
        public static string Zone55 {
            get {
                return ResourceManager.GetString("Zone55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Кувейт, Эр-Рияд.
        /// </summary>
        public static string Zone56 {
            get {
                return ResourceManager.GetString("Zone56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Найроби.
        /// </summary>
        public static string Zone57 {
            get {
                return ResourceManager.GetString("Zone57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:30) Тегеран.
        /// </summary>
        public static string Zone58 {
            get {
                return ResourceManager.GetString("Zone58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Абу-Даби, Мускат.
        /// </summary>
        public static string Zone59 {
            get {
                return ResourceManager.GetString("Zone59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-08:00) Тихоокеанское время (США и Канада).
        /// </summary>
        public static string Zone6 {
            get {
                return ResourceManager.GetString("Zone6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Баку.
        /// </summary>
        public static string Zone60 {
            get {
                return ResourceManager.GetString("Zone60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Волгоград, Москва, Санкт-Петербург.
        /// </summary>
        public static string Zone61 {
            get {
                return ResourceManager.GetString("Zone61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Ереван.
        /// </summary>
        public static string Zone62 {
            get {
                return ResourceManager.GetString("Zone62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Порт-Луи.
        /// </summary>
        public static string Zone63 {
            get {
                return ResourceManager.GetString("Zone63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Тбилиси.
        /// </summary>
        public static string Zone64 {
            get {
                return ResourceManager.GetString("Zone64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:30) Кабул.
        /// </summary>
        public static string Zone65 {
            get {
                return ResourceManager.GetString("Zone65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:00) Исламабад, Карачи.
        /// </summary>
        public static string Zone66 {
            get {
                return ResourceManager.GetString("Zone66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:00) Ташкент.
        /// </summary>
        public static string Zone67 {
            get {
                return ResourceManager.GetString("Zone67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:30) Колката, Мумбаи, Нью-Дели, Ченнай.
        /// </summary>
        public static string Zone68 {
            get {
                return ResourceManager.GetString("Zone68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:30) Шри-Джаявардене-пура-Котте.
        /// </summary>
        public static string Zone69 {
            get {
                return ResourceManager.GetString("Zone69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-07:00) Аризона.
        /// </summary>
        public static string Zone7 {
            get {
                return ResourceManager.GetString("Zone7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:45) Катманду.
        /// </summary>
        public static string Zone70 {
            get {
                return ResourceManager.GetString("Zone70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+06:00) Астана.
        /// </summary>
        public static string Zone71 {
            get {
                return ResourceManager.GetString("Zone71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+06:00) Дакка.
        /// </summary>
        public static string Zone72 {
            get {
                return ResourceManager.GetString("Zone72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+06:00) Екатеринбург.
        /// </summary>
        public static string Zone73 {
            get {
                return ResourceManager.GetString("Zone73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+06:30) Янгон.
        /// </summary>
        public static string Zone74 {
            get {
                return ResourceManager.GetString("Zone74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+07:00) Бангкок, Джакарта, Ханой.
        /// </summary>
        public static string Zone75 {
            get {
                return ResourceManager.GetString("Zone75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+07:00) Новосибирск.
        /// </summary>
        public static string Zone76 {
            get {
                return ResourceManager.GetString("Zone76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Гонконг, Пекин, Урумчи, Чунцин.
        /// </summary>
        public static string Zone77 {
            get {
                return ResourceManager.GetString("Zone77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Красноярск.
        /// </summary>
        public static string Zone78 {
            get {
                return ResourceManager.GetString("Zone78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Куала-Лумпур, Сингапур.
        /// </summary>
        public static string Zone79 {
            get {
                return ResourceManager.GetString("Zone79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-07:00) Горное время (США и Канада).
        /// </summary>
        public static string Zone8 {
            get {
                return ResourceManager.GetString("Zone8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Перт.
        /// </summary>
        public static string Zone80 {
            get {
                return ResourceManager.GetString("Zone80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Тайбэй.
        /// </summary>
        public static string Zone81 {
            get {
                return ResourceManager.GetString("Zone81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Улан-Батор.
        /// </summary>
        public static string Zone82 {
            get {
                return ResourceManager.GetString("Zone82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:00) Иркутск.
        /// </summary>
        public static string Zone83 {
            get {
                return ResourceManager.GetString("Zone83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:00) Осака, Саппоро, Токио.
        /// </summary>
        public static string Zone84 {
            get {
                return ResourceManager.GetString("Zone84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:00) Сеул.
        /// </summary>
        public static string Zone85 {
            get {
                return ResourceManager.GetString("Zone85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:30) Аделаида.
        /// </summary>
        public static string Zone86 {
            get {
                return ResourceManager.GetString("Zone86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:30) Дарвин.
        /// </summary>
        public static string Zone87 {
            get {
                return ResourceManager.GetString("Zone87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:00) Брисбен.
        /// </summary>
        public static string Zone88 {
            get {
                return ResourceManager.GetString("Zone88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:00) Гуам, Порт-Морсби.
        /// </summary>
        public static string Zone89 {
            get {
                return ResourceManager.GetString("Zone89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-07:00) Ла-Пас, Мазатлан, Чихуахуа.
        /// </summary>
        public static string Zone9 {
            get {
                return ResourceManager.GetString("Zone9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:00) Канберра, Мельбурн, Сидней.
        /// </summary>
        public static string Zone90 {
            get {
                return ResourceManager.GetString("Zone90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:00) Хобарт.
        /// </summary>
        public static string Zone91 {
            get {
                return ResourceManager.GetString("Zone91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:00) Якутск.
        /// </summary>
        public static string Zone92 {
            get {
                return ResourceManager.GetString("Zone92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+11:00) Владивосток.
        /// </summary>
        public static string Zone93 {
            get {
                return ResourceManager.GetString("Zone93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+11:00) Соломоновы о-ва, Нов. Каледония.
        /// </summary>
        public static string Zone94 {
            get {
                return ResourceManager.GetString("Zone94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+12:00) Веллингтон, Окленд.
        /// </summary>
        public static string Zone95 {
            get {
                return ResourceManager.GetString("Zone95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+12:00) Время в формате UTC +12.
        /// </summary>
        public static string Zone96 {
            get {
                return ResourceManager.GetString("Zone96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+12:00) Магадан.
        /// </summary>
        public static string Zone97 {
            get {
                return ResourceManager.GetString("Zone97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+12:00) Петропавловск-Камчатский — устаревшее.
        /// </summary>
        public static string Zone98 {
            get {
                return ResourceManager.GetString("Zone98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+12:00) Фиджи.
        /// </summary>
        public static string Zone99 {
            get {
                return ResourceManager.GetString("Zone99", resourceCulture);
            }
        }
    }
}
