//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resto.Front.PrintTemplates.Cheques.Razor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resto.Front.PrintTemplates.Cheques.Razor.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Cheques.Razor
        ///@using Resto.Front.PrintTemplates.Cheques.Razor.TemplateModels
        ///
        ///@inherits TemplateBase&lt;IBanquetPreliminaryCheque&gt;
        ///@{
        ///    var banquet = Model.Banquet;
        ///    var order = banquet.Order;
        ///    if (order == null)
        ///    {
        ///        throw new InvalidOperationException(&quot;Banquet&apos;s order cannot be null.&quot;);
        ///    }
        ///}
        ///
        ///&lt;doc&gt;
        ///    &lt;f2&gt;&lt;center&gt;@string.Format(Resources.BanquetNumberServiceChequeHeaderTe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BanquetPreliminaryCheque {
            get {
                return ResourceManager.GetString("BanquetPreliminaryCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Globalization
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Cheques.Razor
        ///@using Resto.Front.PrintTemplates.Cheques.Razor.TemplateModels
        ///
        ///@inherits TemplateBase&lt;IBillCheque&gt;
        ///@{
        ///    var order = Model.Order;
        ///}
        ///
        ///&lt;doc&gt;
        ///    @* Header (begin) *@
        ///    &lt;whitespace-preserve&gt;@Raw(string.Join(Environment.NewLine, Model.Extensions.BeforeHeader))&lt;/whitespace-preserve&gt;
        ///    &lt;left&gt;&lt;split&gt;&lt;whitespace-preserve&gt;@Model.CommonInfo.CafeSetup.BillH [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BillCheque {
            get {
                return ResourceManager.GetString("BillCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System.Collections.Generic
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Cheques.Razor
        ///@using Resto.Front.PrintTemplates.Cheques.Razor.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@inherits TemplateBase&lt;ICashMemoCheque&gt;
        ///@{
        ///    var order = Model.Order;
        ///    var chequeInfo = Model.ChequeInfo;
        ///    var session = chequeInfo.Session;
        ///    var notDeletedItems = order.Guests.SelectMany(guest =&gt; guest.Items).Where(item =&gt; item.DeletionInfo == null).ToList();
        ///    var ful [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CashMemoCheque {
            get {
                return ResourceManager.GetString("CashMemoCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using Resto.Front.PrintTemplates.Cheques.Razor
        ///@using Resto.Front.PrintTemplates.Cheques.Razor.TemplateModels
        ///
        ///@inherits TemplateBase&lt;ICashRegisterChequeAddition&gt;
        ///@{
        ///    
        ///}
        ///
        ///&lt;doc&gt;
        ///    @* Insert cheque markup here *@
        ///&lt;/doc&gt;.
        /// </summary>
        public static string CashRegisterChequeAddition {
            get {
                return ResourceManager.GetString("CashRegisterChequeAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System.Linq
        ///@using Resto.Front.PrintTemplates.Cheques.Razor
        ///@using Resto.Front.PrintTemplates.Cheques.Razor.TemplateModels
        ///
        ///@inherits TemplateBase&lt;ICookingCompleteCheque&gt;
        ///            
        ///@{
        ///    var order = Model.Order;
        ///
        ///    IKitchenOrderProductItem productItem;
        ///    IKitchenOrderProductItem compoundItemSecondaryComponent = null;
        ///    IKitchenOrderModifierItem modifierItem;
        ///
        ///    if (Model.Item is IKitchenOrderProductItem)
        ///    {
        ///        productItem = (IKitchenOrderProductItem)Model.Item;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CookingCompleteCheque {
            get {
                return ResourceManager.GetString("CookingCompleteCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System.Collections.Generic
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Cheques.Razor.TemplateModels
        ///
        ///@inherits Resto.Front.PrintTemplates.Cheques.Razor.TemplateBase&lt;ICookingCompleteSticker&gt;
        ///@{
        ///    var order = Model.Order;
        ///    
        ///    IKitchenOrderItem actualEntry;
        ///    IKitchenOrderItem compoundItemSecondaryComponent = null;
        ///    if (Model.Modifier != null)
        ///    {
        ///        actualEntry = Model.Modifier;
        ///    }
        ///    else
        ///    {
        ///        actualEntry = Model.Item;
        ///        compoundItemSecon [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CookingCompleteSticker {
            get {
                return ResourceManager.GetString("CookingCompleteSticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System.Linq
        ///@using Resto.Front.PrintTemplates.Cheques.Razor.TemplateModels
        ///
        ///@inherits Resto.Front.PrintTemplates.Cheques.Razor.TemplateBase&lt;ICourierRouteList&gt;
        ///&lt;doc bell=&quot;&quot;&gt;
        ///    @Body()
        ///&lt;/doc&gt;
        ///
        ///@helper Body()
        ///{
        ///    var deliveries = Model.Deliveries.ToList();
        ///    
        ///    &lt;center&gt;
        ///      @string.Format(Resources.DeliveryRouteList)
        ///    &lt;/center&gt;
        ///    &lt;np /&gt;
        ///    for (var positionInRouteList = 0; positionInRouteList &lt; deliveries.Count; positionInRouteList++)
        ///    {
        ///        var delivery = delive [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CourierRouteList {
            get {
                return ResourceManager.GetString("CourierRouteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Cheques.Razor
        ///@using Resto.Front.PrintTemplates.Cheques.Razor.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@inherits TemplateBase&lt;IDeliveryBillCheque&gt;
        ///&lt;doc bell=&quot;&quot;&gt;
        ///    @Header()
        ///    @Body()
        ///    @Footer()
        ///&lt;/doc&gt;
        ///
        ///@helper Header()
        ///{
        ///    var delivery = Model.Delivery;
        ///    var customer = delivery.Customer;
        ///    var address = delivery.Address;
        ///    var cafeSetup = Model.CommonInfo.CafeSetup;
        ///  
        ///    &lt;white [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DeliveryBillCheque {
            get {
                return ResourceManager.GetString("DeliveryBillCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Cheques.Razor.TemplateModels
        ///
        ///@inherits Resto.Front.PrintTemplates.Cheques.Razor.TemplateBase&lt;IDeliverySticker&gt;
        ///@{
        ///    var delivery = Model.Delivery;
        ///    var itemGuest = delivery.Order.Guests.Single(guest =&gt; guest.Items.Contains(Model.Item));
        ///
        ///    IOrderEntry actualEntry;
        ///    IProductItem compoundItemSecondaryComponent = null;
        ///    if (Model.Modifier != null)
        ///    {
        ///        actualEntry = Model.Mo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DeliverySticker {
            get {
                return ResourceManager.GetString("DeliverySticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using Resto.Front.PrintTemplates.Cheques.Razor.TemplateModels
        ///
        ///@inherits Resto.Front.PrintTemplates.Cheques.Razor.TemplateBase&lt;IIikoCardCheque&gt;
        ///
        ///@{
        ///  var cardInfo = Model.CardInfo;
        ///  var order = Model.Order;
        ///}
        ///
        ///&lt;doc&gt;
        ///  &lt;left&gt;
        ///    &lt;split&gt;
        ///      &lt;whitespace-preserve&gt;@Model.CommonInfo.CafeSetup.BillHeader&lt;/whitespace-preserve&gt;
        ///    &lt;/split&gt;
        ///  &lt;/left&gt;
        ///  &lt;np /&gt;
        ///  &lt;left&gt;
        ///    &lt;split&gt;
        ///      @FormatFullDateTime(Model.CommonInfo.CurrentTime)
        ///    &lt;/split&gt;
        ///  &lt;/left&gt;
        ///  &lt;center&gt;
        ///    @cardInfo.Operat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IikoCard {
            get {
                return ResourceManager.GetString("IikoCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @inherits Resto.Front.PrintTemplates.Cheques.Razor.TemplateBase&lt;Resto.Front.PrintTemplates.Cheques.Razor.TemplateModels.IIikoCardShortCheque&gt;
        ///
        ///@{ var cardInfo = Model.CardInfo; }
        ///
        ///&lt;doc&gt;
        ///  &lt;left&gt;
        ///    &lt;wrap&gt;
        ///      @Resources.IikoCardCardNumber@cardInfo.CardNumber
        ///    &lt;/wrap&gt;
        ///  &lt;/left&gt;
        ///
        ///  &lt;left&gt;
        ///    &lt;wrap&gt;
        ///      @Resources.IikoCardCardOwner@cardInfo.CardOwner
        ///    &lt;/wrap&gt;
        ///  &lt;/left&gt;
        ///
        ///  &lt;left&gt;
        ///    &lt;wrap&gt;
        ///      @Resources.IikoCardRowSum@FormatMoney(cardInfo.Amount)
        ///    &lt;/wrap&gt;
        ///  &lt;/left&gt;
        ///
        ///  @ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IikoCardShort {
            get {
                return ResourceManager.GetString("IikoCardShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System.Collections.Generic
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Cheques.Razor
        ///@using Resto.Front.PrintTemplates.Cheques.Razor.TemplateModels
        ///
        ///@inherits TemplateBase&lt;IPastOrderCashMemoCheque&gt;
        ///
        ///@{
        ///  var order = Model.Order;
        ///  var chequeInfo = Model.ChequeInfo;
        ///  var session = chequeInfo.Session;
        ///
        ///  bool useAggregatedDiscount;
        ///  if (order.Items.Count() &lt; 2)
        ///  {
        ///    useAggregatedDiscount = true;
        ///  }
        ///  else
        ///  {
        ///    const decimal MaxGeneralDiscountDeviation = 0.01m;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PastOrderCashMemoCheque {
            get {
                return ResourceManager.GetString("PastOrderCashMemoCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using Resto.Front.PrintTemplates.Cheques.Razor.TemplateModels
        ///
        ///@inherits Resto.Front.PrintTemplates.Cheques.Razor.TemplateBase&lt;IPayInOut&gt;
        ///
        ///&lt;doc&gt;
        ///  @if (!Model.ChequeInfo.IsForReport)
        ///  {
        ///    &lt;left&gt;
        ///      &lt;split&gt;
        ///        &lt;whitespace-preserve&gt;@Model.CommonInfo.CafeSetup.BillHeader&lt;/whitespace-preserve&gt;
        ///      &lt;/split&gt;
        ///    &lt;/left&gt;
        ///  }
        ///  &lt;center&gt;
        ///    @(Model.Event.IsPayIn ? Resources.PayIn : Resources.PayOut)
        ///  &lt;/center&gt;
        ///  @if (Model.Event.IsChangePayIn)
        ///  {
        ///    &lt;pair left=&quot;@Resources.PayInOut [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PayInOut {
            get {
                return ResourceManager.GetString("PayInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using Resto.Front.PrintTemplates.Cheques.Razor.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@inherits Resto.Front.PrintTemplates.Cheques.Razor.TemplateBase&lt;IPrepayCheque&gt;
        ///
        ///&lt;doc&gt;
        ///    &lt;center&gt;@(Model.IsReturn ? Resources.PrepayReturnCheque : Resources.PrepayCheque)&lt;/center&gt;
        ///    &lt;pair left=&quot;@Resources.CurrentDate&quot; right=&quot;@FormatLongDateTime(Model.ChequeInfo.OperationTime)&quot; /&gt;
        ///    &lt;pair left=&quot;@string.Format(Resources.BillHeaderCashierPattern, Model.ChequeInfo.Cashier.Name)&quot; right [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PrepayCheque {
            get {
                return ResourceManager.GetString("PrepayCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System.Collections.Generic;
        ///
        ///@inherits Resto.Front.PrintTemplates.Cheques.Razor.TemplateBase&lt;Resto.Front.PrintTemplates.Cheques.Razor.TemplateModels.IPriceTicket&gt;
        ///
        ///&lt;doc&gt;
        ///  &lt;center&gt;
        ///    @Model.CommonInfo.CafeSetup.LegalName
        ///  &lt;/center&gt;
        ///  &lt;f1&gt;
        ///    &lt;center&gt;
        ///      @Model.Product.Name
        ///    &lt;/center&gt;
        ///  &lt;/f1&gt;
        ///  &lt;left&gt;
        ///    &lt;wrap&gt;
        ///      @{
        ///        var lines = new List&lt;string&gt;();
        ///        
        ///        lines.Add(Resources.BarcodeAmount);
        ///        lines.Add(FormatAmount(Model.Amount));
        ///
        ///        lin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PriceTicket {
            get {
                return ResourceManager.GetString("PriceTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Globalization
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Cheques.Razor
        ///@using Resto.Front.PrintTemplates.Cheques.Razor.TemplateModels
        ///
        ///@inherits TemplateBase&lt;IReceiptCheque&gt;
        ///@{
        ///    var chequeTask = Model.ChequeTask;
        ///    var order = Model.Order;
        ///    var sum = chequeTask.Sales.Sum(sale =&gt; sale.GetCost() - sale.DiscountSum + sale.IncreaseSum).RoundMoney();
        ///}
        ///
        ///&lt;doc&gt;
        ///    @if (!Model.ChequeInfo.IsForReport)
        ///    {
        ///        &lt;left&gt;&lt;split&gt;&lt;whitespace-preserve&gt;@Mode [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReceiptCheque {
            get {
                return ResourceManager.GetString("ReceiptCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Cheques.Razor
        ///@using Resto.Front.PrintTemplates.Cheques.Razor.TemplateModels
        ///
        ///@inherits TemplateBase&lt;IServiceChequeBase&gt;
        ///
        ///&lt;doc bell=&quot;&quot; formatter=&quot;split&quot;&gt;
        ///    @if (Model is IServiceCheque)
        ///    {
        ///        @Service((IServiceCheque)Model)
        ///    }
        ///    else if (Model is IBanquetServiceCheque)
        ///    {
        ///        @Banquet((IBanquetServiceCheque)Model)
        ///    }
        ///    else if (Model is IDeleteProductsServiceCheque [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ServiceCheque {
            get {
                return ResourceManager.GetString("ServiceCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System.Globalization
        ///@using System.Linq
        ///
        ///@inherits Resto.Front.PrintTemplates.Cheques.Razor.TemplateBase&lt;Resto.Front.PrintTemplates.Cheques.Razor.TemplateModels.ITablesReserve&gt;
        ///            
        ///@{
        ///  var reserve = Model.Reserve;
        ///  var customer = reserve.Customer;
        ///}
        ///
        ///&lt;doc&gt;
        ///  &lt;center&gt;
        ///    @Resources.TablesReserveHeaderTitle
        ///  &lt;/center&gt;
        ///  &lt;np /&gt;
        ///  &lt;center&gt;
        ///    @string.Format(Resources.ReserveNumberFormat, reserve.IsBanquet ? Resources.BanquetReserveType : Resources.ReserveReserveType, reserve [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TablesReserve {
            get {
                return ResourceManager.GetString("TablesReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using Resto.Front.PrintTemplates.Cheques.Razor.TemplateModels
        ///
        ///@inherits Resto.Front.PrintTemplates.Cheques.Razor.TemplateBase&lt;IVatInvoice&gt;
        ///@{
        ///    
        ///}
        ///
        ///&lt;doc&gt;
        ///    @* Insert cheque markup here *@
        ///&lt;/doc&gt;.
        /// </summary>
        public static string VatInvoice {
            get {
                return ResourceManager.GetString("VatInvoice", resourceCulture);
            }
        } 
    }
}
