//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resto.Front.PrintTemplates.Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resto.Front.PrintTemplates.Reports.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Diagnostics
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@* 048 Итого по смене *@
        ///@inherits TemplateBase
        ///@{
        ///    if (Model.CafeSession == null)
        ///    {
        ///        &lt;doc&gt;&lt;center&gt;@Resources.CafeSessionIsClosed&lt;/center&gt;&lt;/doc&gt;
        ///        return;
        ///    }
        ///    FillData();
        ///}
        ///
        ///@if (!Model.IsOnlyBodyMarkupRequired)
        ///{
        ///    &lt;d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CafeSessionSummaryReport {
            get {
                return ResourceManager.GetString("CafeSessionSummaryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///
        ///@* 053 Блюда для приготовления доставок *@
        ///@inherits TemplateBase
        ///@{
        ///    settings = Model.ReportSettings;
        ///    groupByCookingPlaces = settings.GetBool(&quot;GroupByCookingPlaces&quot;);
        ///
        ///    deliveriesInfo.Clear();
        ///    deliveriesInfoByCookingPlaces.Clear();
        ///
        ///    var allNotSendDeliveriesInPeriod = Model.Entities.GetAllNotDeletedDeliveries() [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DeliveryDishesReport {
            get {
                return ResourceManager.GetString("DeliveryDishesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Diagnostics
        ///@using System.Linq
        ///@using Resto.Framework.Common
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@* 054 Отчет по чаевым *@
        ///@inherits Resto.Front.PrintTemplates.Reports.TemplateBase
        ///@{
        ///    if (Model.CafeSession == null)
        ///    {
        ///        &lt;doc&gt;&lt;center&gt;@Resources.CafeSessionIsClosed&lt;/center&gt;&lt;/doc&gt;
        ///        return;
        ///    }
        ///    FillData();
        ///}
        ///
        ///@if (!Model.IsOnlyBodyMa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DonationsReport {
            get {
                return ResourceManager.GetString("DonationsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///
        ///@* 039 Отчет по вскрытия тары *@
        ///@inherits TemplateBase
        ///@{
        ///    FillData();
        ///}
        ///
        ///@if (!Model.IsOnlyBodyMarkupRequired)
        ///{
        ///    &lt;doc formatter=&quot;split&quot;&gt;
        ///        @Header()
        ///        @Body()
        ///    &lt;/doc&gt;
        ///}
        ///else
        ///{
        ///    &lt;doc formatter=&quot;split&quot;&gt;
        ///        @Body()
        ///    &lt;/doc&gt;
        ///}
        ///
        ///@helper Header()
        ///{
        ///    var terminalName = Model.CashRegiste [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EgaisProductUnsealReport {
            get {
                return ResourceManager.GetString("EgaisProductUnsealReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Diagnostics
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@inherits TemplateBase
        ///@{
        ///    if (Model.CafeSession == null)
        ///    {
        ///        &lt;doc&gt;&lt;center&gt;@Resources.CafeSessionIsClosed&lt;/center&gt;&lt;/doc&gt;
        ///        return;
        ///    }
        ///    settings = Model.ReportSettings;
        ///    FillData();
        ///    ClearZeroDebts();
        ///}
        ///
        ///@if (!Model.I [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmployeeDebtsReport {
            get {
                return ResourceManager.GetString("EmployeeDebtsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Diagnostics
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@* 033 Время от пречека до оплаты *@
        ///@* Отчет по кассовым данным *@
        ///@inherits TemplateBase
        ///@{
        ///    if (Model.CafeSession == null)
        ///    {
        ///        &lt;doc&gt;&lt;center&gt;@Resources.CafeSessionIsClosed&lt;/center&gt;&lt;/doc&gt;
        ///        return;
        ///    }
        ///    FillData();
        ///}
        ///
        ///@if (!Model.IsOnlyBodyMarkupRequired)
        ///{
        ///    &lt;doc formatter=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrderGapReport {
            get {
                return ResourceManager.GetString("OrderGapReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@inherits TemplateBase
        ///@{
        ///    var session = Model.CafeSession;
        ///    if (session == null)
        ///    {
        ///        &lt;doc&gt;&lt;center&gt;@Resources.CafeSessionIsClosed&lt;/center&gt;&lt;/doc&gt;
        ///        return;
        ///    }
        ///
        ///    var ordersBySections = Model.Entities.GetAllNotDeletedNotBoundToNonStartedReservesOrdersB [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrdersSummaryReport {
            get {
                return ResourceManager.GetString("OrdersSummaryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Diagnostics
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@* 052 Отчет по внесениям и изъятиям *@
        ///@inherits TemplateBase
        ///@{
        ///    if (Model.CafeSession == null)
        ///    {
        ///        &lt;doc&gt;&lt;center&gt;@Resources.CafeSessionIsClosed&lt;/center&gt;&lt;/doc&gt;
        ///        return;
        ///    }
        ///    FillData();
        ///}
        ///
        ///@if (!Model.IsOnlyBodyMarkupRequi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PayInOutReport {
            get {
                return ResourceManager.GetString("PayInOutReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Diagnostics
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///@using IOrder = Resto.Front.PrintTemplates.Reports.TemplateModels.IOrder
        ///
        ///@* 037 Опасные операции *@
        ///@inherits Resto.Front.PrintTemplates.Reports.TemplateBase
        ///@{
        ///    var settings = Model.ReportSettings;
        ///    Debug.Assert(settings != null);
        ///    allEvents = Model.Entities.GetProblemOperationsEvents( [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProblemOperationsReport {
            get {
                return ResourceManager.GetString("ProblemOperationsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.OlapReports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@* 016 Чеки по типам оплаты *@
        ///@* Парный к 047-му отчет по серверным данным *@
        ///@inherits TemplateBase
        ///@{
        ///    settings = Model.ReportSettings;
        ///
        ///    FillData();
        ///}
        ///
        ///@if (!Model.IsOnlyBodyMarkupRequired)
        ///{
        ///    &lt;doc formatter [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SalesByPaymentTypeServerReport {
            get {
                return ResourceManager.GetString("SalesByPaymentTypeServerReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Diagnostics
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@* 047 Чеки по типам оплаты за смену *@
        ///@* Парный к 016-му отчет по кассовым данным *@
        ///@inherits TemplateBase
        ///@{
        ///    if (Model.CafeSession == null)
        ///    {
        ///        &lt;doc&gt;&lt;center&gt;@Resources.CafeSessionIsClosed&lt;/center&gt;&lt;/doc&gt;
        ///        return;
        ///    }
        ///    Fil [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SalesByPaymentTypeSessionReport {
            get {
                return ResourceManager.GetString("SalesByPaymentTypeSessionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.OlapReports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@* 011 Общая выручка по типам с налогами *@
        ///@* Парный к 041-му отчет по серверным данным *@
        ///@inherits TemplateBase
        ///@{
        ///    settings = Model.ReportSettings;
        ///    
        ///    FillSalesData();
        ///    FillTaxesData();
        ///}
        ///
        ///@if (!Model.IsOn [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SalesByTypeWithTaxServerReport {
            get {
                return ResourceManager.GetString("SalesByTypeWithTaxServerReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Diagnostics
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@* 041 Выручка по типам с налогами *@
        ///@* Парный к 011-му отчет по кассовым данным *@
        ///@inherits TemplateBase
        ///@{
        ///    if (Model.CafeSession == null)
        ///    {
        ///        &lt;doc&gt;&lt;center&gt;@Resources.CafeSessionIsClosed&lt;/center&gt;&lt;/doc&gt;
        ///        return;
        ///    }
        ///
        ///    Fil [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SalesByTypeWithTaxSessionReport {
            get {
                return ResourceManager.GetString("SalesByTypeWithTaxSessionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.OlapReports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@inherits TemplateBase
        ///@{
        ///    settings = Model.ReportSettings;
        ///    
        ///    FillData();
        ///}
        ///
        ///@if (!Model.IsOnlyBodyMarkupRequired)
        ///{
        ///    &lt;doc formatter=&quot;split&quot;&gt;
        ///        @Header()
        ///        @Body()
        ///        @Footer()
        ///    &lt;/doc&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SalesByWaiterServerReport {
            get {
                return ResourceManager.GetString("SalesByWaiterServerReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Diagnostics
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.OlapReports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@* 021 Общий расход блюд *@
        ///@* Парный к 044-му отчет по серверным данным *@
        ///@inherits TemplateBase
        ///@{
        ///    settings = Model.ReportSettings;
        ///    
        ///    FillData();
        ///    ClearZeroSales();
        ///}
        ///
        ///@if (!Mod [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ServerExpenseReport {
            get {
                return ResourceManager.GetString("ServerExpenseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.OlapReports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///
        ///@* 012 Общая выручка почасовая *@
        ///@* Парный к 042-му отчет по серверным данным *@
        ///@inherits TemplateBase
        ///@{
        ///    settings = Model.ReportSettings;
        ///
        ///    FillData();
        ///}
        ///
        ///@if (!Model.IsOnlyBodyMarkupRequired)
        ///{
        ///    &lt;doc formatter=&quot;split&quot;&gt;
        ///        @Header()
        ///        @Body()
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ServerHourlyReport {
            get {
                return ResourceManager.GetString("ServerHourlyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.OlapReports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@* 023 Общие продажи блюд *@
        ///@* Парный к 043-му отчет по серверным данным *@
        ///@inherits TemplateBase
        ///@{
        ///    settings = Model.ReportSettings;
        ///
        ///    FillAdvancePayProducts();
        ///    FillSales();
        ///    ClearZeroSales();
        ///}
        ///
        ///@if (!M [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ServerSalesReport {
            get {
                return ResourceManager.GetString("ServerSalesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Diagnostics
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.OlapReports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@* 024 Общие списания блюд *@
        ///@* Парный к 034-му отчет по серверным данным *@
        ///@inherits TemplateBase
        ///@{
        ///    settings = Model.ReportSettings;
        ///    
        ///    FillData();
        ///}
        ///
        ///@if (!Model.IsOnlyBodyMarkupRe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ServerWriteoffReport {
            get {
                return ResourceManager.GetString("ServerWriteoffReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@* 050 Отчет по доставкам *@
        ///@inherits Resto.Front.PrintTemplates.Reports.TemplateBase
        ///@{
        ///    settings = Model.ReportSettings;
        ///
        ///    FillData();
        ///}
        ///
        ///@if (!Model.IsOnlyBodyMarkupRequired)
        ///{
        ///    &lt;doc formatter=&quot;split&quot;&gt;
        ///        @Header()
        ///        @Body()
        ///        @Footer()
        ///    &lt;/doc&gt;
        ///}
        ///else
        ///{
        ///    &lt;doc formatter=&quot;spli [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SessionDeliveriesReport {
            get {
                return ResourceManager.GetString("SessionDeliveriesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Diagnostics
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@inherits TemplateBase
        ///@{
        ///    if (Model.CafeSession == null)
        ///    {
        ///        &lt;doc&gt;&lt;center&gt;@Resources.CafeSessionIsClosed&lt;/center&gt;&lt;/doc&gt;
        ///        return;
        ///    }
        ///    FillData();
        ///}
        ///
        ///@if (!Model.IsOnlyBodyMarkupRequired)
        ///{
        ///    &lt;doc formatter=&quot;split&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SessionDiscountReport {
            get {
                return ResourceManager.GetString("SessionDiscountReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Diagnostics
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@* 044 Расход блюд *@
        ///@* Парный к 021-му отчет по кассовым данным *@
        ///@inherits TemplateBase
        ///@{
        ///    if (Model.CafeSession == null)
        ///    {
        ///        &lt;doc&gt;&lt;center&gt;@Resources.CafeSessionIsClosed&lt;/center&gt;&lt;/doc&gt;
        ///        return;
        ///    }
        ///    settings = Model.Repo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SessionExpenseReport {
            get {
                return ResourceManager.GetString("SessionExpenseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Diagnostics
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///
        ///@* 042 Выручка почасовая *@
        ///@* Парный к 012-му отчет по кассовым данным *@
        ///@inherits TemplateBase
        ///@{
        ///    if (Model.CafeSession == null)
        ///    {
        ///        &lt;doc&gt;&lt;center&gt;@Resources.CafeSessionIsClosed&lt;/center&gt;&lt;/doc&gt;
        ///        return;
        ///    }
        ///    settings = Model.ReportSettings;
        ///
        ///    FillData();
        ///}
        ///
        ///@if (!Mode [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SessionHourlyReport {
            get {
                return ResourceManager.GetString("SessionHourlyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@* 051 Расширенный реестр счетов *@
        ///@* Парный к 046 кассовый отчет по нефискальным оплатам *@
        ///@inherits TemplateBase
        ///@{
        ///    var session = Model.CafeSession;
        ///    if (session == null)
        ///    {
        ///        &lt;doc&gt;&lt;center&gt;@Resources.CafeSessionIsClosed&lt;/center&gt;&lt;/doc&gt;
        ///        return;
        ///    }        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SessionSalesExtendedRegisterReport {
            get {
                return ResourceManager.GetString("SessionSalesExtendedRegisterReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@* 046 Реестр счетов *@
        ///@* Парный к 051 кассовый отчет по фискальным оплатам *@
        ///@inherits TemplateBase
        ///@{
        ///    var session = Model.CafeSession;
        ///    if (session == null)
        ///    {
        ///        &lt;doc&gt;&lt;center&gt;@Resources.CafeSessionIsClosed&lt;/center&gt;&lt;/doc&gt;
        ///        return;
        ///    }
        ///    
        ///    Mod [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SessionSalesRegisterReport {
            get {
                return ResourceManager.GetString("SessionSalesRegisterReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Diagnostics
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@* 043 Продажи блюд *@
        ///@* Парный к 023-му отчет по кассовым данным *@
        ///@inherits TemplateBase
        ///@{
        ///    if (Model.CafeSession == null)
        ///    {
        ///        &lt;doc&gt;&lt;center&gt;@Resources.CafeSessionIsClosed&lt;/center&gt;&lt;/doc&gt;
        ///        return;
        ///    }
        ///    settings = Model.Rep [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SessionSalesReport {
            get {
                return ResourceManager.GetString("SessionSalesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Diagnostics
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@* 034 Списания блюд *@
        ///@* Парный к 024-му отчет по кассовым данным *@
        ///@inherits TemplateBase
        ///@{
        ///    if (Model.CafeSession == null)
        ///    {
        ///        &lt;doc&gt;&lt;center&gt;@Resources.CafeSessionIsClosed&lt;/center&gt;&lt;/doc&gt;
        ///        return;
        ///    }
        ///    settings = Model.Re [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SessionWriteoffReport {
            get {
                return ResourceManager.GetString("SessionWriteoffReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Globalization
        ///@using System.Linq
        ///@using Resto.Front.PrintTemplates.Reports.TemplateModels
        ///@using Resto.Front.PrintTemplates.RmsEntityWrappers
        ///
        ///@inherits Resto.Front.PrintTemplates.Reports.TemplateBase
        ///@{
        ///    var operationsCount = new OperationsCounter();
        ///    var payInOutData = new PayInOutData();
        ///
        ///    var payments = Model.Entities.GetAllPaymentTypes()
        ///      .ToDictionary(pt =&gt; pt, _ =&gt; new PaymentData());
        ///
        ///    var session = Model.C [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XReport {
            get {
                return ResourceManager.GetString("XReport", resourceCulture);
            }
        }
    }
}
