//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resto.Front.PrintTemplates.Cheques.Xslt {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resto.Front.PrintTemplates.Cheques.Xslt.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;x:stylesheet version=&quot;1.0&quot; xmlns:x=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;x:output method=&quot;xml&quot; version=&quot;1.0&quot; encoding=&quot;utf-8&quot; indent=&quot;yes&quot; /&gt;
        ///
        ///  &lt;x:variable name=&quot;Res&quot; select=&quot;/*/Settings/Resources&quot; /&gt;
        ///  &lt;!-- ChequeLocalResources (strings as attrs) --&gt;
        ///
        ///  &lt;!-- Пречек --&gt;
        ///  &lt;x:template match=&quot;/Bill&quot;&gt;
        ///    &lt;doc&gt;
        ///      &lt;!-- Header (begin) --&gt;
        ///      &lt;x:copy-of select=&quot;Extensions/BeforeHeader/*&quot; /&gt;
        ///      &lt;left&gt;
        ///        &lt;split&gt;
        ///          &lt;x:value-of select [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BillCheque {
            get {
                return ResourceManager.GetString("BillCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;x:stylesheet version=&quot;1.0&quot; xmlns:x=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;x:output method=&quot;xml&quot; version=&quot;1.0&quot; encoding=&quot;utf-8&quot; indent=&quot;yes&quot; /&gt;
        ///
        ///  &lt;x:variable name=&quot;Res&quot; select=&quot;/*/Settings/Resources&quot; /&gt;
        ///  &lt;!-- ChequeLocalResources (strings as attrs) --&gt;
        ///
        ///  &lt;!-- Чек: ошибка, неподдерживаемый корень XML --&gt;
        ///  &lt;x:template match=&quot;/*&quot;&gt;
        ///    &lt;doc&gt;
        ///      &lt;f2&gt;ОШИБКА&lt;/f2&gt;
        ///      &lt;f1&gt;
        ///        Неподдерживаемый тип чеков: &lt;x:value-of select=&quot;name(/*)&quot; /&gt;
        ///      &lt;/f1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CashCheque {
            get {
                return ResourceManager.GetString("CashCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;x:stylesheet version=&quot;1.0&quot; xmlns:x=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;x:output method=&quot;xml&quot; version=&quot;1.0&quot; encoding=&quot;utf-8&quot; indent=&quot;yes&quot; /&gt;
        ///
        ///  &lt;!-- ChequeLocalResources (strings as attrs) --&gt;
        ///  &lt;x:variable name=&quot;Res&quot; select=&quot;/*/Settings/Resources&quot; /&gt;
        ///
        ///  &lt;!-- Чек: товарный чек --&gt;
        ///  &lt;x:template match=&quot;/CashMemo&quot;&gt;
        ///    &lt;doc&gt;
        ///      &lt;!-- header --&gt;
        ///      &lt;left&gt;
        ///        &lt;split&gt;
        ///          &lt;x:value-of select=&quot;Settings/@ChequeHeader&quot; /&gt;
        ///        &lt;/split&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CashMemoCheque {
            get {
                return ResourceManager.GetString("CashMemoCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;x:stylesheet version=&quot;1.0&quot; xmlns:x=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;x:output method=&quot;xml&quot; version=&quot;1.0&quot; encoding=&quot;utf-8&quot; indent=&quot;yes&quot; /&gt;
        ///
        ///  &lt;x:variable name=&quot;Res&quot; select=&quot;/*/Settings/Resources&quot; /&gt;
        ///  &lt;!-- ChequeLocalResources (strings as attrs) --&gt;
        ///  &lt;x:variable name=&quot;CommonBillFooter&quot; select=&quot;/*/BillFooter/@Value&quot; /&gt;
        ///
        ///  &lt;!-- Чек: ошибка, неподдерживаемый корень XML --&gt;
        ///  &lt;x:template match=&quot;/*&quot;&gt;
        ///    &lt;doc&gt;
        ///      &lt;f2&gt;ОШИБКА&lt;/f2&gt;
        ///      &lt;f1&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DeliveryBillCheque {
            get {
                return ResourceManager.GetString("DeliveryBillCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;x:stylesheet version=&quot;1.0&quot; xmlns:x=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;x:output method=&quot;xml&quot; version=&quot;1.0&quot; encoding=&quot;utf-8&quot; indent=&quot;yes&quot; /&gt;
        ///
        ///  &lt;x:variable name=&quot;Res&quot; select=&quot;/*/Settings/Resources&quot; /&gt;
        ///  &lt;!-- ChequeLocalResources (strings as attrs) --&gt;
        ///
        ///  &lt;!-- Стикер --&gt;
        ///  &lt;x:template match=&quot;/DeliverySticker&quot;&gt;
        ///    &lt;doc&gt;
        ///      &lt;center&gt;
        ///        &lt;x:value-of select=&quot;Settings/@EnterpriseName&quot;/&gt;
        ///      &lt;/center&gt;
        ///      &lt;left&gt;
        ///        &lt;wrap&gt;
        ///          &lt;x:va [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DeliverySticker {
            get {
                return ResourceManager.GetString("DeliverySticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;x:stylesheet version=&quot;1.0&quot; xmlns:x=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;x:output method=&quot;xml&quot; version=&quot;1.0&quot; encoding=&quot;utf-8&quot; indent=&quot;yes&quot; /&gt;
        ///
        ///  &lt;x:variable name=&quot;Res&quot; select=&quot;/*/Settings/Resources&quot; /&gt;
        ///
        ///  &lt;!-- Чек: ошибка, неподдерживаемый корень XML --&gt;
        ///  &lt;x:template match=&quot;/*&quot;&gt;
        ///    &lt;doc&gt;
        ///      &lt;f2&gt;ОШИБКА&lt;/f2&gt;
        ///      &lt;f1&gt;
        ///        Неподдерживаемый тип чеков: &lt;x:value-of select=&quot;name(/*)&quot; /&gt;
        ///      &lt;/f1&gt;
        ///    &lt;/doc&gt;
        ///  &lt;/x:template&gt;
        ///
        ///  &lt;!-- iikoCard -- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IikoCard {
            get {
                return ResourceManager.GetString("IikoCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;x:stylesheet version=&quot;1.0&quot; xmlns:x=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;x:output method=&quot;xml&quot; version=&quot;1.0&quot; encoding=&quot;utf-8&quot; indent=&quot;yes&quot; /&gt;
        ///
        ///  &lt;x:variable name=&quot;Res&quot; select=&quot;/*/Settings/Resources&quot; /&gt;
        ///  &lt;!-- ChequeLocalResources (strings as attrs) --&gt;
        ///
        ///  &lt;!-- Этикетка --&gt;
        ///  &lt;x:template match=&quot;/PriceTicket&quot;&gt;
        ///    &lt;doc&gt;
        ///      &lt;center&gt;
        ///        &lt;x:value-of select=&quot;Settings/@EnterpriseName&quot;/&gt;
        ///      &lt;/center&gt;
        ///      &lt;f1&gt;
        ///        &lt;center&gt;
        ///          &lt;x:valu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PriceTicket {
            get {
                return ResourceManager.GetString("PriceTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;x:stylesheet version=&quot;1.0&quot; xmlns:x=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;x:output method=&quot;xml&quot; version=&quot;1.0&quot; encoding=&quot;utf-8&quot; indent=&quot;yes&quot; /&gt;
        ///
        ///  &lt;x:variable name=&quot;Res&quot; select=&quot;/*/Settings/Resources&quot; /&gt;
        ///  &lt;!-- ChequeLocalResources (strings as attrs) --&gt;
        ///
        ///  &lt;!-- Чек: ошибка, неподдерживаемый корень XML --&gt;
        ///  &lt;x:template match=&quot;/*&quot;&gt;
        ///    &lt;doc&gt;
        ///      &lt;f2&gt;ОШИБКА&lt;/f2&gt;
        ///      &lt;f1&gt;
        ///        Неподдерживаемый тип чеков: &lt;x:value-of select=&quot;name(/*)&quot; /&gt;
        ///      &lt;/f1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ServiceCheque {
            get {
                return ResourceManager.GetString("ServiceCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;x:stylesheet version=&quot;1.0&quot; xmlns:x=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;x:output method=&quot;xml&quot; version=&quot;1.0&quot; encoding=&quot;utf-8&quot; indent=&quot;yes&quot; /&gt;
        ///
        ///  &lt;x:variable name=&quot;Res&quot; select=&quot;/*/Settings/Resources&quot; /&gt;
        ///  &lt;!-- ChequeLocalResources (strings as attrs) --&gt;
        ///
        ///  &lt;x:template match=&quot;/TablesReserve&quot;&gt;
        ///    &lt;x:variable name=&quot;StartDate&quot; select=&quot;substring(/*/@StartTime, 1, 10)&quot; /&gt;
        ///    &lt;x:variable name=&quot;EndDate&quot; select=&quot;substring(/*/@EndTime, 1, 10)&quot; /&gt;
        ///
        ///    &lt;doc&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TablesReserveInfo {
            get {
                return ResourceManager.GetString("TablesReserveInfo", resourceCulture);
            }
        }
    }
}
