//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resto.Front.PrintTemplates.StimulSoftReports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resto.Front.PrintTemplates.StimulSoftReports.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;StiSerializer version=&quot;1.02&quot; type=&quot;Net&quot; application=&quot;StiReport&quot;&gt;
        ///  &lt;Dictionary Ref=&quot;1&quot; type=&quot;Dictionary&quot; isKey=&quot;true&quot;&gt;
        ///    &lt;BusinessObjects isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;Databases isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;DataSources isList=&quot;true&quot; count=&quot;3&quot;&gt;
        ///      &lt;CookingCompleteStickerPrimaryItem Ref=&quot;2&quot; type=&quot;Stimulsoft.Report.Dictionary.StiBusinessObjectSource&quot; isKey=&quot;true&quot;&gt;
        ///        &lt;Alias&gt;CookingCompleteStickerPrimaryItem&lt;/Alias&gt;
        ///        &lt;Columns [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CookingCompleteSticker {
            get {
                return ResourceManager.GetString("CookingCompleteSticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;StiSerializer version=&quot;1.02&quot; type=&quot;Net&quot; application=&quot;StiReport&quot;&gt;
        ///  &lt;Dictionary Ref=&quot;1&quot; type=&quot;Dictionary&quot; isKey=&quot;true&quot;&gt;
        ///    &lt;BusinessObjects isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;Databases isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;DataSources isList=&quot;true&quot; count=&quot;1&quot;&gt;
        ///      &lt;DeliveryInRouteListInfo Ref=&quot;2&quot; type=&quot;Stimulsoft.Report.Dictionary.StiBusinessObjectSource&quot; isKey=&quot;true&quot;&gt;
        ///        &lt;Alias&gt;DeliveryInRouteListInfo&lt;/Alias&gt;
        ///        &lt;Columns isList=&quot;true&quot; count [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CourierRouteListReport {
            get {
                return ResourceManager.GetString("CourierRouteListReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;StiSerializer version=&quot;1.02&quot; type=&quot;Net&quot; application=&quot;StiReport&quot;&gt;
        ///  &lt;CacheAllData&gt;True&lt;/CacheAllData&gt;
        ///  &lt;Dictionary Ref=&quot;1&quot; type=&quot;Dictionary&quot; isKey=&quot;true&quot;&gt;
        ///    &lt;BusinessObjects isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;Databases isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;DataSources isList=&quot;true&quot; count=&quot;12&quot;&gt;
        ///      &lt;DeliveryInfo Ref=&quot;2&quot; type=&quot;Stimulsoft.Report.Dictionary.StiBusinessObjectSource&quot; isKey=&quot;true&quot;&gt;
        ///        &lt;Alias&gt;DeliveryInfo&lt;/Alias&gt;
        ///        &lt;Columns isL [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DeliveryInvoiceReport {
            get {
                return ResourceManager.GetString("DeliveryInvoiceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;StiSerializer version=&quot;1.02&quot; type=&quot;Net&quot; application=&quot;StiReport&quot;&gt;
        ///  &lt;Dictionary Ref=&quot;1&quot; type=&quot;Dictionary&quot; isKey=&quot;true&quot;&gt;
        ///    &lt;BusinessObjects isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;Databases isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;DataSources isList=&quot;true&quot; count=&quot;3&quot;&gt;
        ///      &lt;DeliveryStickerPrimaryItem Ref=&quot;2&quot; type=&quot;Stimulsoft.Report.Dictionary.StiBusinessObjectSource&quot; isKey=&quot;true&quot;&gt;
        ///        &lt;Alias&gt;DeliveryStickerPrimaryItem&lt;/Alias&gt;
        ///        &lt;Columns isList=&quot;true&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DeliverySticker {
            get {
                return ResourceManager.GetString("DeliverySticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;StiSerializer version=&quot;1.02&quot; type=&quot;Net&quot; application=&quot;StiReport&quot;&gt;
        ///  &lt;Dictionary Ref=&quot;1&quot; type=&quot;Dictionary&quot; isKey=&quot;true&quot;&gt;
        ///    &lt;BusinessObjects isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;Databases isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;DataSources isList=&quot;true&quot; count=&quot;4&quot;&gt;
        ///      &lt;InvoiceBillTemplateProperties Ref=&quot;2&quot; type=&quot;DataTableSource&quot; isKey=&quot;true&quot;&gt;
        ///        &lt;Alias&gt;InvoiceBillTemplateProperties&lt;/Alias&gt;
        ///        &lt;Columns isList=&quot;true&quot; count=&quot;32&quot;&gt;
        ///          &lt;value&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InvoiceBillReport {
            get {
                return ResourceManager.GetString("InvoiceBillReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;StiSerializer version=&quot;1.02&quot; type=&quot;Net&quot; application=&quot;StiReport&quot;&gt;
        ///  &lt;Dictionary Ref=&quot;1&quot; type=&quot;Dictionary&quot; isKey=&quot;true&quot;&gt;
        ///    &lt;BusinessObjects isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;Databases isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;DataSources isList=&quot;true&quot; count=&quot;3&quot;&gt;
        ///      &lt;DeliveryStickerPrimaryItem Ref=&quot;2&quot; type=&quot;Stimulsoft.Report.Dictionary.StiBusinessObjectSource&quot; isKey=&quot;true&quot;&gt;
        ///        &lt;Alias&gt;DeliveryStickerPrimaryItem&lt;/Alias&gt;
        ///        &lt;Columns isList=&quot;true&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PriceTicket {
            get {
                return ResourceManager.GetString("PriceTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;StiSerializer version=&quot;1.02&quot; type=&quot;Net&quot; application=&quot;StiReport&quot;&gt;
        ///  &lt;Dictionary Ref=&quot;1&quot; type=&quot;Dictionary&quot; isKey=&quot;true&quot;&gt;
        ///    &lt;BusinessObjects isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;Databases isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;DataSources isList=&quot;true&quot; count=&quot;2&quot;&gt;
        ///      &lt;Torg12TemplateProperties Ref=&quot;2&quot; type=&quot;DataTableSource&quot; isKey=&quot;true&quot;&gt;
        ///        &lt;Alias&gt;Torg12TemplateProperties&lt;/Alias&gt;
        ///        &lt;Columns isList=&quot;true&quot; count=&quot;24&quot;&gt;
        ///          &lt;value&gt;Date,Syste [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Torg12Report {
            get {
                return ResourceManager.GetString("Torg12Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;StiSerializer version=&quot;1.02&quot; type=&quot;Net&quot; application=&quot;StiReport&quot;&gt;
        ///  &lt;Dictionary Ref=&quot;1&quot; type=&quot;Dictionary&quot; isKey=&quot;true&quot;&gt;
        ///    &lt;BusinessObjects isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;Databases isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;DataSources isList=&quot;true&quot; count=&quot;4&quot;&gt;
        ///      &lt;GeneralInfo Ref=&quot;2&quot; type=&quot;Stimulsoft.Report.Dictionary.StiBusinessObjectSource&quot; isKey=&quot;true&quot;&gt;
        ///        &lt;Alias&gt;GeneralInfo&lt;/Alias&gt;
        ///        &lt;Columns isList=&quot;true&quot; count=&quot;7&quot;&gt;
        ///          &lt;value&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VatInvoiceReport {
            get {
                return ResourceManager.GetString("VatInvoiceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;StiSerializer version=&quot;1.02&quot; type=&quot;Net&quot; application=&quot;StiReport&quot;&gt;
        ///  &lt;Dictionary Ref=&quot;1&quot; type=&quot;Dictionary&quot; isKey=&quot;true&quot;&gt;
        ///    &lt;BusinessObjects isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;Databases isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;DataSources isList=&quot;true&quot; count=&quot;4&quot;&gt;
        ///      &lt;GeneralInfo Ref=&quot;2&quot; type=&quot;Stimulsoft.Report.Dictionary.StiBusinessObjectSource&quot; isKey=&quot;true&quot;&gt;
        ///        &lt;Alias&gt;GeneralInfo&lt;/Alias&gt;
        ///        &lt;Columns isList=&quot;true&quot; count=&quot;9&quot;&gt;
        ///          &lt;value&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VatInvoiceShortenedReport {
            get {
                return ResourceManager.GetString("VatInvoiceShortenedReport", resourceCulture);
            }
        }
    }
}
