//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://plustech/giftcardservice", ConfigurationName="GiftCardServiceSoap")]
public interface GiftCardServiceSoap
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/LogUser", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    LogUserResponse LogUser(LogUserRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/OpenShift", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    OpenShiftResponse OpenShift(OpenShiftRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/CloseShift", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    CloseShiftResponse CloseShift(CloseShiftRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/ActivateCard", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ActivateCardResponse ActivateCard(ActivateCardRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/ActivateCardEx", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ActivateCardExResponse ActivateCardEx(ActivateCardExRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/ActivateFreeCard", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ActivateFreeCardResponse ActivateFreeCard(ActivateFreeCardRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/RedeemCard", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    RedeemCardResponse RedeemCard(RedeemCardRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/RedeemCardEx", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    RedeemCardExResponse RedeemCardEx(RedeemCardExRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/RedeemCardDiscount", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    RedeemCardDiscountResponse RedeemCardDiscount(RedeemCardDiscountRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/ProcessPurchase", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ProcessPurchaseResponse ProcessPurchase(ProcessPurchaseRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/ActivateBonus", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ActivateBonusResponse ActivateBonus(ActivateBonusRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/ActivateRedeemCard", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ActivateRedeemCardResponse ActivateRedeemCard(ActivateRedeemCardRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/AuthorizeAmount", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    AuthorizeAmountResponse AuthorizeAmount(AuthorizeAmountRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/VoidAuthorization", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    VoidAuthorizationResponse VoidAuthorization(VoidAuthorizationRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/ConfirmAuthorization", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ConfirmAuthorizationResponse ConfirmAuthorization(ConfirmAuthorizationRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/AddAmount", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    AddAmountResponse AddAmount(AddAmountRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/AddAmountEx", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    AddAmountExResponse AddAmountEx(AddAmountExRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/AddFreeAmount", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    AddFreeAmountResponse AddFreeAmount(AddFreeAmountRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/AddRedeemCard", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    AddRedeemCardResponse AddRedeemCard(AddRedeemCardRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/AddBonus", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    AddBonusResponse AddBonus(AddBonusRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/ReturnAmount", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ReturnAmountResponse ReturnAmount(ReturnAmountRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/RecallBonus", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    RecallBonusResponse RecallBonus(RecallBonusRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/ReturnDepositAmount", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ReturnDepositAmountResponse ReturnDepositAmount(ReturnDepositAmountRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/AdjustBalance", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    AdjustBalanceResponse AdjustBalance(AdjustBalanceRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/VoidTransaction", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    VoidTransactionResponse VoidTransaction(VoidTransactionRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/ReplaceCard", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ReplaceCardResponse ReplaceCard(ReplaceCardRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/ChangePIN", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ChangePINResponse ChangePIN(ChangePINRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/GetCardInfo", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetCardInfoResponse GetCardInfo(GetCardInfoRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/GetCustomerInfoByCard", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetCustomerInfoByCardResponse GetCustomerInfoByCard(GetCustomerInfoByCardRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/CancelCard", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    CancelCardResponse CancelCard(CancelCardRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/StopCard", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    StopCardResponse StopCard(StopCardRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/RestoreCard", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    RestoreCardResponse RestoreCard(RestoreCardRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/GetTransReport", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetTransReportResponse GetTransReport(GetTransReportRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/GetTranHistoryReport", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetTranHistoryReportResponse GetTranHistoryReport(GetTranHistoryReportRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/GetTranSummaryReport", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetTranSummaryReportResponse GetTranSummaryReport(GetTranSummaryReportRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/GetCardTranHistoryReport", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetCardTranHistoryReportResponse GetCardTranHistoryReport(GetCardTranHistoryReportRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://plustech/giftcardservice/RemoveCard", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    RemoveCardResponse RemoveCard(RemoveCardRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://plustech/giftcardservice")]
public partial class TranObject
{
    
    private string cardNumberField;
    
    private string pINField;
    
    private int cardTypeField;
    
    private string actTimeField;
    
    private string expTimeField;
    
    private double amountField;
    
    private double balanceField;
    
    private int statusField;
    
    private int merchantIDField;
    
    private int locationIDField;
    
    private string terminalIDField;
    
    private string loginField;
    
    private string passwordField;
    
    private string operTimeField;
    
    private int transactionIDField;
    
    private double currentDiscountField;
    
    private double bonusAmountField;
    
    private int childTransactionIDField;
    
    private double bonusPercentField;
    
    private double convertedAmountField;
    
    private int voidTransactionIDField;
    
    private string replacedCardNumberField;
    
    private string lastUsedTimeField;
    
    private string reserved_1Field;
    
    private string reserved_2Field;
    
    private string reserved_3Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0, IsNullable = true)]
    public string CardNumber
    {
        get
        {
            return this.cardNumberField;
        }
        set
        {
            this.cardNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1, IsNullable = true)]
    public string PIN
    {
        get
        {
            return this.pINField;
        }
        set
        {
            this.pINField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public int CardType
    {
        get
        {
            return this.cardTypeField;
        }
        set
        {
            this.cardTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3, IsNullable = true)]
    public string ActTime
    {
        get
        {
            return this.actTimeField;
        }
        set
        {
            this.actTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4, IsNullable = true)]
    public string ExpTime
    {
        get
        {
            return this.expTimeField;
        }
        set
        {
            this.expTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public double Amount
    {
        get
        {
            return this.amountField;
        }
        set
        {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public double Balance
    {
        get
        {
            return this.balanceField;
        }
        set
        {
            this.balanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
    public int Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
    public int MerchantID
    {
        get
        {
            return this.merchantIDField;
        }
        set
        {
            this.merchantIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
    public int LocationID
    {
        get
        {
            return this.locationIDField;
        }
        set
        {
            this.locationIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 10, IsNullable = true)]
    public string TerminalID
    {
        get
        {
            return this.terminalIDField;
        }
        set
        {
            this.terminalIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 11, IsNullable = true)]
    public string Login
    {
        get
        {
            return this.loginField;
        }
        set
        {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 12, IsNullable = true)]
    public string Password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 13, IsNullable = true)]
    public string OperTime
    {
        get
        {
            return this.operTimeField;
        }
        set
        {
            this.operTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
    public int TransactionID
    {
        get
        {
            return this.transactionIDField;
        }
        set
        {
            this.transactionIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
    public double CurrentDiscount
    {
        get
        {
            return this.currentDiscountField;
        }
        set
        {
            this.currentDiscountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
    public double BonusAmount
    {
        get
        {
            return this.bonusAmountField;
        }
        set
        {
            this.bonusAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
    public int ChildTransactionID
    {
        get
        {
            return this.childTransactionIDField;
        }
        set
        {
            this.childTransactionIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
    public double BonusPercent
    {
        get
        {
            return this.bonusPercentField;
        }
        set
        {
            this.bonusPercentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 19)]
    public double ConvertedAmount
    {
        get
        {
            return this.convertedAmountField;
        }
        set
        {
            this.convertedAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 20)]
    public int VoidTransactionID
    {
        get
        {
            return this.voidTransactionIDField;
        }
        set
        {
            this.voidTransactionIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 21, IsNullable = true)]
    public string ReplacedCardNumber
    {
        get
        {
            return this.replacedCardNumberField;
        }
        set
        {
            this.replacedCardNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 22, IsNullable = true)]
    public string LastUsedTime
    {
        get
        {
            return this.lastUsedTimeField;
        }
        set
        {
            this.lastUsedTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 23, IsNullable = true)]
    public string Reserved_1
    {
        get
        {
            return this.reserved_1Field;
        }
        set
        {
            this.reserved_1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 24, IsNullable = true)]
    public string Reserved_2
    {
        get
        {
            return this.reserved_2Field;
        }
        set
        {
            this.reserved_2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 25, IsNullable = true)]
    public string Reserved_3
    {
        get
        {
            return this.reserved_3Field;
        }
        set
        {
            this.reserved_3Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://plustech/giftcardservice")]
public partial class ReportTranObject
{
    
    private string cardNumberField;
    
    private int programIDField;
    
    private int merchantIDField;
    
    private int locationIDField;
    
    private string terminalIDField;
    
    private string startTimeField;
    
    private string endTimeField;
    
    private int timeOffsetField;
    
    private string loginField;
    
    private string passwordField;
    
    private int maxRecordsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string CardNumber
    {
        get
        {
            return this.cardNumberField;
        }
        set
        {
            this.cardNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int ProgramID
    {
        get
        {
            return this.programIDField;
        }
        set
        {
            this.programIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public int MerchantID
    {
        get
        {
            return this.merchantIDField;
        }
        set
        {
            this.merchantIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public int LocationID
    {
        get
        {
            return this.locationIDField;
        }
        set
        {
            this.locationIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string TerminalID
    {
        get
        {
            return this.terminalIDField;
        }
        set
        {
            this.terminalIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string StartTime
    {
        get
        {
            return this.startTimeField;
        }
        set
        {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string EndTime
    {
        get
        {
            return this.endTimeField;
        }
        set
        {
            this.endTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public int TimeOffset
    {
        get
        {
            return this.timeOffsetField;
        }
        set
        {
            this.timeOffsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string Login
    {
        get
        {
            return this.loginField;
        }
        set
        {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public string Password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public int MaxRecords
    {
        get
        {
            return this.maxRecordsField;
        }
        set
        {
            this.maxRecordsField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="LogUser", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class LogUserRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public LogUserRequest()
    {
    }
    
    public LogUserRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="LogUserResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class LogUserResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public LogUserResponse()
    {
    }
    
    public LogUserResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="OpenShift", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class OpenShiftRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public OpenShiftRequest()
    {
    }
    
    public OpenShiftRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="OpenShiftResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class OpenShiftResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public OpenShiftResponse()
    {
    }
    
    public OpenShiftResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="CloseShift", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class CloseShiftRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public CloseShiftRequest()
    {
    }
    
    public CloseShiftRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="CloseShiftResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class CloseShiftResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public CloseShiftResponse()
    {
    }
    
    public CloseShiftResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ActivateCard", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ActivateCardRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public ActivateCardRequest()
    {
    }
    
    public ActivateCardRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ActivateCardResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ActivateCardResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public ActivateCardResponse()
    {
    }
    
    public ActivateCardResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ActivateCardEx", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ActivateCardExRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public ActivateCardExRequest()
    {
    }
    
    public ActivateCardExRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ActivateCardExResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ActivateCardExResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public ActivateCardExResponse()
    {
    }
    
    public ActivateCardExResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ActivateFreeCard", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ActivateFreeCardRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public ActivateFreeCardRequest()
    {
    }
    
    public ActivateFreeCardRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ActivateFreeCardResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ActivateFreeCardResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public ActivateFreeCardResponse()
    {
    }
    
    public ActivateFreeCardResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RedeemCard", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class RedeemCardRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public RedeemCardRequest()
    {
    }
    
    public RedeemCardRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RedeemCardResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class RedeemCardResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public RedeemCardResponse()
    {
    }
    
    public RedeemCardResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RedeemCardEx", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class RedeemCardExRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public RedeemCardExRequest()
    {
    }
    
    public RedeemCardExRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RedeemCardExResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class RedeemCardExResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public RedeemCardExResponse()
    {
    }
    
    public RedeemCardExResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RedeemCardDiscount", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class RedeemCardDiscountRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public RedeemCardDiscountRequest()
    {
    }
    
    public RedeemCardDiscountRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RedeemCardDiscountResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class RedeemCardDiscountResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public RedeemCardDiscountResponse()
    {
    }
    
    public RedeemCardDiscountResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ProcessPurchase", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ProcessPurchaseRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public int MerchantID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=1)]
    public int LocationID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=2)]
    public string TerminalID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=3)]
    public string Login;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=4)]
    public string Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=5)]
    public string CardNumber;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=6)]
    public string PIN;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=7)]
    public int CardType;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=8)]
    public int AuthID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=9)]
    public double Amount;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=10)]
    public double GoodsAmount;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=11)]
    public int GoodsCount;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=12)]
    public string GoodsData;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=13)]
    public int ExtraDataInCount;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=14)]
    public string ExtraDataIn;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=15)]
    public double Balance;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=16)]
    public double BonusAmount;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=17)]
    public double TotalRedeemAmount;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=18)]
    public string ExpTime;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=19)]
    public string OperTime;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=20)]
    public int TranID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=21)]
    public int BonusTranID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=22)]
    public int ExtraDataOutCount;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=23)]
    public string ExtraDataOut;
    
    public ProcessPurchaseRequest()
    {
    }
    
    public ProcessPurchaseRequest(
                int MerchantID, 
                int LocationID, 
                string TerminalID, 
                string Login, 
                string Password, 
                string CardNumber, 
                string PIN, 
                int CardType, 
                int AuthID, 
                double Amount, 
                double GoodsAmount, 
                int GoodsCount, 
                string GoodsData, 
                int ExtraDataInCount, 
                string ExtraDataIn, 
                double Balance, 
                double BonusAmount, 
                double TotalRedeemAmount, 
                string ExpTime, 
                string OperTime, 
                int TranID, 
                int BonusTranID, 
                int ExtraDataOutCount, 
                string ExtraDataOut)
    {
        this.MerchantID = MerchantID;
        this.LocationID = LocationID;
        this.TerminalID = TerminalID;
        this.Login = Login;
        this.Password = Password;
        this.CardNumber = CardNumber;
        this.PIN = PIN;
        this.CardType = CardType;
        this.AuthID = AuthID;
        this.Amount = Amount;
        this.GoodsAmount = GoodsAmount;
        this.GoodsCount = GoodsCount;
        this.GoodsData = GoodsData;
        this.ExtraDataInCount = ExtraDataInCount;
        this.ExtraDataIn = ExtraDataIn;
        this.Balance = Balance;
        this.BonusAmount = BonusAmount;
        this.TotalRedeemAmount = TotalRedeemAmount;
        this.ExpTime = ExpTime;
        this.OperTime = OperTime;
        this.TranID = TranID;
        this.BonusTranID = BonusTranID;
        this.ExtraDataOutCount = ExtraDataOutCount;
        this.ExtraDataOut = ExtraDataOut;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ProcessPurchaseResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ProcessPurchaseResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public double Balance;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=1)]
    public double BonusAmount;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=2)]
    public double TotalRedeemAmount;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=3)]
    public string ExpTime;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=4)]
    public string OperTime;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=5)]
    public int TranID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=6)]
    public int BonusTranID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=7)]
    public int ExtraDataOutCount;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=8)]
    public string ExtraDataOut;
    
    public ProcessPurchaseResponse()
    {
    }
    
    public ProcessPurchaseResponse(double Balance, double BonusAmount, double TotalRedeemAmount, string ExpTime, string OperTime, int TranID, int BonusTranID, int ExtraDataOutCount, string ExtraDataOut)
    {
        this.Balance = Balance;
        this.BonusAmount = BonusAmount;
        this.TotalRedeemAmount = TotalRedeemAmount;
        this.ExpTime = ExpTime;
        this.OperTime = OperTime;
        this.TranID = TranID;
        this.BonusTranID = BonusTranID;
        this.ExtraDataOutCount = ExtraDataOutCount;
        this.ExtraDataOut = ExtraDataOut;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ActivateBonus", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ActivateBonusRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public ActivateBonusRequest()
    {
    }
    
    public ActivateBonusRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ActivateBonusResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ActivateBonusResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public ActivateBonusResponse()
    {
    }
    
    public ActivateBonusResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ActivateRedeemCard", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ActivateRedeemCardRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public ActivateRedeemCardRequest()
    {
    }
    
    public ActivateRedeemCardRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ActivateRedeemCardResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ActivateRedeemCardResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public ActivateRedeemCardResponse()
    {
    }
    
    public ActivateRedeemCardResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="AuthorizeAmount", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class AuthorizeAmountRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public AuthorizeAmountRequest()
    {
    }
    
    public AuthorizeAmountRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="AuthorizeAmountResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class AuthorizeAmountResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public AuthorizeAmountResponse()
    {
    }
    
    public AuthorizeAmountResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="VoidAuthorization", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class VoidAuthorizationRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public VoidAuthorizationRequest()
    {
    }
    
    public VoidAuthorizationRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="VoidAuthorizationResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class VoidAuthorizationResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public VoidAuthorizationResponse()
    {
    }
    
    public VoidAuthorizationResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmAuthorization", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ConfirmAuthorizationRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public ConfirmAuthorizationRequest()
    {
    }
    
    public ConfirmAuthorizationRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmAuthorizationResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ConfirmAuthorizationResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public ConfirmAuthorizationResponse()
    {
    }
    
    public ConfirmAuthorizationResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="AddAmount", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class AddAmountRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public AddAmountRequest()
    {
    }
    
    public AddAmountRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="AddAmountResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class AddAmountResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public AddAmountResponse()
    {
    }
    
    public AddAmountResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="AddAmountEx", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class AddAmountExRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public AddAmountExRequest()
    {
    }
    
    public AddAmountExRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="AddAmountExResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class AddAmountExResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public AddAmountExResponse()
    {
    }
    
    public AddAmountExResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="AddFreeAmount", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class AddFreeAmountRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public AddFreeAmountRequest()
    {
    }
    
    public AddFreeAmountRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="AddFreeAmountResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class AddFreeAmountResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public AddFreeAmountResponse()
    {
    }
    
    public AddFreeAmountResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="AddRedeemCard", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class AddRedeemCardRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public AddRedeemCardRequest()
    {
    }
    
    public AddRedeemCardRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="AddRedeemCardResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class AddRedeemCardResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public AddRedeemCardResponse()
    {
    }
    
    public AddRedeemCardResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="AddBonus", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class AddBonusRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public AddBonusRequest()
    {
    }
    
    public AddBonusRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="AddBonusResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class AddBonusResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public AddBonusResponse()
    {
    }
    
    public AddBonusResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ReturnAmount", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ReturnAmountRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public ReturnAmountRequest()
    {
    }
    
    public ReturnAmountRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ReturnAmountResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ReturnAmountResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public ReturnAmountResponse()
    {
    }
    
    public ReturnAmountResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RecallBonus", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class RecallBonusRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public RecallBonusRequest()
    {
    }
    
    public RecallBonusRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RecallBonusResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class RecallBonusResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public RecallBonusResponse()
    {
    }
    
    public RecallBonusResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ReturnDepositAmount", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ReturnDepositAmountRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public ReturnDepositAmountRequest()
    {
    }
    
    public ReturnDepositAmountRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ReturnDepositAmountResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ReturnDepositAmountResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public ReturnDepositAmountResponse()
    {
    }
    
    public ReturnDepositAmountResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="AdjustBalance", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class AdjustBalanceRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public AdjustBalanceRequest()
    {
    }
    
    public AdjustBalanceRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="AdjustBalanceResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class AdjustBalanceResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public AdjustBalanceResponse()
    {
    }
    
    public AdjustBalanceResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="VoidTransaction", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class VoidTransactionRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public VoidTransactionRequest()
    {
    }
    
    public VoidTransactionRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="VoidTransactionResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class VoidTransactionResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public VoidTransactionResponse()
    {
    }
    
    public VoidTransactionResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ReplaceCard", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ReplaceCardRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public ReplaceCardRequest()
    {
    }
    
    public ReplaceCardRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ReplaceCardResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ReplaceCardResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public ReplaceCardResponse()
    {
    }
    
    public ReplaceCardResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ChangePIN", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ChangePINRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public ChangePINRequest()
    {
    }
    
    public ChangePINRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ChangePINResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class ChangePINResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public ChangePINResponse()
    {
    }
    
    public ChangePINResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetCardInfo", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class GetCardInfoRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public GetCardInfoRequest()
    {
    }
    
    public GetCardInfoRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetCardInfoResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class GetCardInfoResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public GetCardInfoResponse()
    {
    }
    
    public GetCardInfoResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerInfoByCard", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class GetCustomerInfoByCardRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public int merchantID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=1)]
    public int locationID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=2)]
    public string terminalID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=3)]
    public string Login;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=4)]
    public string Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=5)]
    public string CardNumber;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=6)]
    public string ClientInfo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=7)]
    public int CustomerLevel;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=8)]
    public int StarsCount;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=9)]
    public int ClientMsgID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=10)]
    public string ClientMsgStr;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=11)]
    public string CustomerData;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=12)]
    public int PromoDataCount;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=13)]
    public string PromoData;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=14)]
    public int ReturnValue;
    
    public GetCustomerInfoByCardRequest()
    {
    }
    
    public GetCustomerInfoByCardRequest(int merchantID, int locationID, string terminalID, string Login, string Password, string CardNumber, string ClientInfo, int CustomerLevel, int StarsCount, int ClientMsgID, string ClientMsgStr, string CustomerData, int PromoDataCount, string PromoData, int ReturnValue)
    {
        this.merchantID = merchantID;
        this.locationID = locationID;
        this.terminalID = terminalID;
        this.Login = Login;
        this.Password = Password;
        this.CardNumber = CardNumber;
        this.ClientInfo = ClientInfo;
        this.CustomerLevel = CustomerLevel;
        this.StarsCount = StarsCount;
        this.ClientMsgID = ClientMsgID;
        this.ClientMsgStr = ClientMsgStr;
        this.CustomerData = CustomerData;
        this.PromoDataCount = PromoDataCount;
        this.PromoData = PromoData;
        this.ReturnValue = ReturnValue;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerInfoByCardResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class GetCustomerInfoByCardResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public string ClientInfo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=1)]
    public int CustomerLevel;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=2)]
    public int StarsCount;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=3)]
    public int ClientMsgID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=4)]
    public string ClientMsgStr;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=5)]
    public string CustomerData;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=6)]
    public int PromoDataCount;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=7)]
    public string PromoData;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=8)]
    public int ReturnValue;
    
    public GetCustomerInfoByCardResponse()
    {
    }
    
    public GetCustomerInfoByCardResponse(string ClientInfo, int CustomerLevel, int StarsCount, int ClientMsgID, string ClientMsgStr, string CustomerData, int PromoDataCount, string PromoData, int ReturnValue)
    {
        this.ClientInfo = ClientInfo;
        this.CustomerLevel = CustomerLevel;
        this.StarsCount = StarsCount;
        this.ClientMsgID = ClientMsgID;
        this.ClientMsgStr = ClientMsgStr;
        this.CustomerData = CustomerData;
        this.PromoDataCount = PromoDataCount;
        this.PromoData = PromoData;
        this.ReturnValue = ReturnValue;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="CancelCard", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class CancelCardRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public CancelCardRequest()
    {
    }
    
    public CancelCardRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="CancelCardResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class CancelCardResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public CancelCardResponse()
    {
    }
    
    public CancelCardResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="StopCard", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class StopCardRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public StopCardRequest()
    {
    }
    
    public StopCardRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="StopCardResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class StopCardResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public StopCardResponse()
    {
    }
    
    public StopCardResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RestoreCard", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class RestoreCardRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public RestoreCardRequest()
    {
    }
    
    public RestoreCardRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RestoreCardResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class RestoreCardResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public RestoreCardResponse()
    {
    }
    
    public RestoreCardResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetTransReport", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class GetTransReportRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public ReportTranObject obj;
    
    public GetTransReportRequest()
    {
    }
    
    public GetTransReportRequest(ReportTranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetTransReportResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class GetTransReportResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public System.Data.DataSet GetTransReportResult;
    
    public GetTransReportResponse()
    {
    }
    
    public GetTransReportResponse(System.Data.DataSet GetTransReportResult)
    {
        this.GetTransReportResult = GetTransReportResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetTranHistoryReport", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class GetTranHistoryReportRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public ReportTranObject obj;
    
    public GetTranHistoryReportRequest()
    {
    }
    
    public GetTranHistoryReportRequest(ReportTranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetTranHistoryReportResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class GetTranHistoryReportResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public string GetTranHistoryReportResult;
    
    public GetTranHistoryReportResponse()
    {
    }
    
    public GetTranHistoryReportResponse(string GetTranHistoryReportResult)
    {
        this.GetTranHistoryReportResult = GetTranHistoryReportResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetTranSummaryReport", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class GetTranSummaryReportRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public ReportTranObject obj;
    
    public GetTranSummaryReportRequest()
    {
    }
    
    public GetTranSummaryReportRequest(ReportTranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetTranSummaryReportResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class GetTranSummaryReportResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public string GetTranSummaryReportResult;
    
    public GetTranSummaryReportResponse()
    {
    }
    
    public GetTranSummaryReportResponse(string GetTranSummaryReportResult)
    {
        this.GetTranSummaryReportResult = GetTranSummaryReportResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetCardTranHistoryReport", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class GetCardTranHistoryReportRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public ReportTranObject obj;
    
    public GetCardTranHistoryReportRequest()
    {
    }
    
    public GetCardTranHistoryReportRequest(ReportTranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetCardTranHistoryReportResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class GetCardTranHistoryReportResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public string GetCardTranHistoryReportResult;
    
    public GetCardTranHistoryReportResponse()
    {
    }
    
    public GetCardTranHistoryReportResponse(string GetCardTranHistoryReportResult)
    {
        this.GetCardTranHistoryReportResult = GetCardTranHistoryReportResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RemoveCard", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class RemoveCardRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public RemoveCardRequest()
    {
    }
    
    public RemoveCardRequest(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RemoveCardResponse", WrapperNamespace="http://plustech/giftcardservice", IsWrapped=true)]
public partial class RemoveCardResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://plustech/giftcardservice", Order=0)]
    public TranObject obj;
    
    public RemoveCardResponse()
    {
    }
    
    public RemoveCardResponse(TranObject obj)
    {
        this.obj = obj;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface GiftCardServiceSoapChannel : GiftCardServiceSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GiftCardServiceSoapClient : System.ServiceModel.ClientBase<GiftCardServiceSoap>, GiftCardServiceSoap
{
    
    public GiftCardServiceSoapClient()
    {
    }
    
    public GiftCardServiceSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public GiftCardServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GiftCardServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GiftCardServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public LogUserResponse LogUser(LogUserRequest request)
    {
        return base.Channel.LogUser(request);
    }
    
    public OpenShiftResponse OpenShift(OpenShiftRequest request)
    {
        return base.Channel.OpenShift(request);
    }
    
    public CloseShiftResponse CloseShift(CloseShiftRequest request)
    {
        return base.Channel.CloseShift(request);
    }
    
    public ActivateCardResponse ActivateCard(ActivateCardRequest request)
    {
        return base.Channel.ActivateCard(request);
    }
    
    public ActivateCardExResponse ActivateCardEx(ActivateCardExRequest request)
    {
        return base.Channel.ActivateCardEx(request);
    }
    
    public ActivateFreeCardResponse ActivateFreeCard(ActivateFreeCardRequest request)
    {
        return base.Channel.ActivateFreeCard(request);
    }
    
    public RedeemCardResponse RedeemCard(RedeemCardRequest request)
    {
        return base.Channel.RedeemCard(request);
    }
    
    public RedeemCardExResponse RedeemCardEx(RedeemCardExRequest request)
    {
        return base.Channel.RedeemCardEx(request);
    }
    
    public RedeemCardDiscountResponse RedeemCardDiscount(RedeemCardDiscountRequest request)
    {
        return base.Channel.RedeemCardDiscount(request);
    }
    
    public ProcessPurchaseResponse ProcessPurchase(ProcessPurchaseRequest request)
    {
        return base.Channel.ProcessPurchase(request);
    }
    
    public ActivateBonusResponse ActivateBonus(ActivateBonusRequest request)
    {
        return base.Channel.ActivateBonus(request);
    }
    
    public ActivateRedeemCardResponse ActivateRedeemCard(ActivateRedeemCardRequest request)
    {
        return base.Channel.ActivateRedeemCard(request);
    }
    
    public AuthorizeAmountResponse AuthorizeAmount(AuthorizeAmountRequest request)
    {
        return base.Channel.AuthorizeAmount(request);
    }
    
    public VoidAuthorizationResponse VoidAuthorization(VoidAuthorizationRequest request)
    {
        return base.Channel.VoidAuthorization(request);
    }
    
    public ConfirmAuthorizationResponse ConfirmAuthorization(ConfirmAuthorizationRequest request)
    {
        return base.Channel.ConfirmAuthorization(request);
    }
    
    public AddAmountResponse AddAmount(AddAmountRequest request)
    {
        return base.Channel.AddAmount(request);
    }
    
    public AddAmountExResponse AddAmountEx(AddAmountExRequest request)
    {
        return base.Channel.AddAmountEx(request);
    }
    
    public AddFreeAmountResponse AddFreeAmount(AddFreeAmountRequest request)
    {
        return base.Channel.AddFreeAmount(request);
    }
    
    public AddRedeemCardResponse AddRedeemCard(AddRedeemCardRequest request)
    {
        return base.Channel.AddRedeemCard(request);
    }
    
    public AddBonusResponse AddBonus(AddBonusRequest request)
    {
        return base.Channel.AddBonus(request);
    }
    
    public ReturnAmountResponse ReturnAmount(ReturnAmountRequest request)
    {
        return base.Channel.ReturnAmount(request);
    }
    
    public RecallBonusResponse RecallBonus(RecallBonusRequest request)
    {
        return base.Channel.RecallBonus(request);
    }
    
    public ReturnDepositAmountResponse ReturnDepositAmount(ReturnDepositAmountRequest request)
    {
        return base.Channel.ReturnDepositAmount(request);
    }
    
    public AdjustBalanceResponse AdjustBalance(AdjustBalanceRequest request)
    {
        return base.Channel.AdjustBalance(request);
    }
    
    public VoidTransactionResponse VoidTransaction(VoidTransactionRequest request)
    {
        return base.Channel.VoidTransaction(request);
    }
    
    public ReplaceCardResponse ReplaceCard(ReplaceCardRequest request)
    {
        return base.Channel.ReplaceCard(request);
    }
    
    public ChangePINResponse ChangePIN(ChangePINRequest request)
    {
        return base.Channel.ChangePIN(request);
    }
    
    public GetCardInfoResponse GetCardInfo(GetCardInfoRequest request)
    {
        return base.Channel.GetCardInfo(request);
    }
    
    public GetCustomerInfoByCardResponse GetCustomerInfoByCard(GetCustomerInfoByCardRequest request)
    {
        return base.Channel.GetCustomerInfoByCard(request);
    }
    
    public CancelCardResponse CancelCard(CancelCardRequest request)
    {
        return base.Channel.CancelCard(request);
    }
    
    public StopCardResponse StopCard(StopCardRequest request)
    {
        return base.Channel.StopCard(request);
    }
    
    public RestoreCardResponse RestoreCard(RestoreCardRequest request)
    {
        return base.Channel.RestoreCard(request);
    }
    
    public GetTransReportResponse GetTransReport(GetTransReportRequest request)
    {
        return base.Channel.GetTransReport(request);
    }
    
    public GetTranHistoryReportResponse GetTranHistoryReport(GetTranHistoryReportRequest request)
    {
        return base.Channel.GetTranHistoryReport(request);
    }
    
    public GetTranSummaryReportResponse GetTranSummaryReport(GetTranSummaryReportRequest request)
    {
        return base.Channel.GetTranSummaryReport(request);
    }
    
    public GetCardTranHistoryReportResponse GetCardTranHistoryReport(GetCardTranHistoryReportRequest request)
    {
        return base.Channel.GetCardTranHistoryReport(request);
    }
    
    public RemoveCardResponse RemoveCard(RemoveCardRequest request)
    {
        return base.Channel.RemoveCard(request);
    }
}
